# Generated by Django 6.0.1 on 2026-02-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_userschoolmembership_role'),
        ('students', '0002_make_parent_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', help_text="Section identifier: 'A', 'B', 'C', or '' for single-section grades", max_length=10),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name: 'Playgroup', 'Nursery', 'Class 1', etc.", max_length=50)),
                ('numeric_level', models.IntegerField(help_text='Numeric sort order: Playgroup=0, Nursery=1, Prep=2, Class 1=3, ...')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['numeric_level'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Grade this class belongs to (for grouping sections)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='students.grade'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('grade__isnull', False)), fields=('school', 'grade', 'section'), name='unique_grade_section_per_school'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'numeric_level')},
        ),
    ]
