# Generated by Django 6.0.1 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_grade_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text="Class name, e.g., 'Class 5-A', 'PlayGroup'", max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', help_text="Section identifier: 'A', 'B', 'C', or '' for single-section classes", max_length=10),
        ),
    ]
