# Generated by Django 5.2.11 on 2026-02-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0007_alter_class_name_alter_class_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHelperMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_helper_messages', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_messages', to='students.student')),
            ],
            options={
                'verbose_name': 'Study Helper Message',
                'verbose_name_plural': 'Study Helper Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
