# Generated by Django 5.2.11 on 2026-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0008_study_helper_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='students_cl_school__a137b4_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'grade_level', 'section'], name='students_cl_school__e467bc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='students_st_school__3f378d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_obj', 'is_active'], name='students_st_class_o_c43ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_obj'], name='students_st_school__59ce9b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_obj', 'roll_number'], name='students_st_school__f6108a_idx'),
        ),
    ]
