# Generated by Django 5.2.11 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_fix_class_name_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated'), ('REPEAT', 'Repeat'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
