# Generated by Django 5.2.11 on 2026-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text="Class name, e.g., 'Class 1', 'PlayGroup'", max_length=50),
        ),
    ]
