# Generated by Django 6.0.4 on 2026-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
