# Generated by Django 5.2.11 on 2026-10-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transferred_from',
            field=models.ForeignKey(blank=True, help_text='The student record this one was created from by a branch transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='students.student'),
        ),
    ]
