# Generated by Django 6.0.1 on 2026-02-13 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_populate_module_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ATTENDANCE_DAILY', 'Daily Attendance'), ('ATTENDANCE_MONTHLY', 'Monthly Attendance'), ('ATTENDANCE_TERM', 'Term Attendance'), ('FEE_COLLECTION', 'Fee Collection Summary'), ('FEE_DEFAULTERS', 'Fee Defaulters List'), ('FEE_RECEIPT', 'Fee Receipt'), ('STUDENT_PROGRESS', 'Student Progress Report'), ('CLASS_RESULT', 'Class Result Summary'), ('STUDENT_COMPREHENSIVE', 'Student Comprehensive Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_url', models.URLField(blank=True, default='')),
                ('file_content', models.BinaryField(blank=True, help_text='In-memory report for direct download', null=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'Excel')], default='PDF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='schools.school')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
