# Generated by Django 5.2.11 on 2026-02-25 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('schools', '0014_school_exam_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.TextField(max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('line_spacing', models.CharField(choices=[('single', 'Single'), ('1.5', '1.5'), ('double', 'Double')], default='single', max_length=10)),
                ('template_type', models.CharField(choices=[('custom', 'Custom'), ('experience', 'Experience Certificate'), ('termination', 'Termination Letter'), ('warning', 'Warning Letter'), ('appreciation', 'Appreciation Letter'), ('leave_approval', 'Leave Approval'), ('salary_increment', 'Salary Increment'), ('transfer', 'Transfer Letter')], default='custom', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_letters', to='schools.school')),
            ],
            options={
                'verbose_name': 'Custom Letter',
                'verbose_name_plural': 'Custom Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
