# Generated by Django 6.0.1 on 2026-02-13 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_populate_module_defaults'),
        ('students', '0003_class_section_grade_class_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message')], max_length=20)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email')], max_length=20)),
                ('subject_template', models.CharField(blank=True, default='', help_text='Title/subject line with {{placeholders}}', max_length=200)),
                ('body_template', models.TextField(help_text='Message body with {{student_name}}, {{class_name}}, {{date}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, help_text='Null = system-wide default template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='schools.school')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['event_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Do not send notifications before this time', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Do not send notifications after this time', null=True)),
                ('fee_reminder_day', models.IntegerField(default=5, help_text='Day of month to send fee reminders (1-28)')),
                ('daily_absence_summary_time', models.TimeField(blank=True, help_text='Time to send daily absence summary to admins', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Notification Config',
                'verbose_name_plural': 'School Notification Configs',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email')], max_length=20)),
                ('event_type', models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='schools.school')),
                ('student', models.ForeignKey(blank=True, help_text='For parent notification preferences (keyed by student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='students.student')),
                ('user', models.ForeignKey(blank=True, help_text='For staff notification preferences', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('school', 'user', 'channel', 'event_type'), name='unique_user_notification_pref'), models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('school', 'student', 'channel', 'event_type'), name='unique_student_notification_pref')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email')], max_length=20)),
                ('event_type', models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('PARENT', 'Parent'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], max_length=20)),
                ('recipient_identifier', models.CharField(help_text='Phone number, user ID, or email', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='API response, error details, extra context')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='notificatio_school__ffe681_idx'), models.Index(fields=['recipient_user', 'status'], name='notificatio_recipie_ee960b_idx'), models.Index(fields=['school', 'event_type'], name='notificatio_school__686cec_idx')],
            },
        ),
    ]
