# Generated by Django 6.0.1 on 2026-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder')], max_length=20),
        ),
    ]
