# Generated by Django 5.2.11 on 2026-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
    ]
