# Generated by Django 5.2.11 on 2026-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_push_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When to dispatch this notification (for AI-optimized scheduling)', null=True),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='smart_scheduling_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, AI analyzes read patterns to schedule non-urgent notifications at optimal times'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20),
        ),
    ]
