# Generated by Django 5.2.11 on 2026-02-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationlog_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='absence_notification_enabled',
            field=models.BooleanField(default=True, help_text='Send notifications to parents when a student is marked absent'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='daily_absence_summary_enabled',
            field=models.BooleanField(default=False, help_text='Send daily absence summary to admins'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='exam_result_enabled',
            field=models.BooleanField(default=True, help_text='Notify parents when exam results are published'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='fee_overdue_enabled',
            field=models.BooleanField(default=True, help_text='Send alerts when fees are completely overdue'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='fee_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Send monthly fee reminders for unpaid/partial fees'),
        ),
    ]
