# Generated by Django 5.2.11 on 2026-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_schoolnotificationconfig_absence_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='transport_notification_enabled',
            field=models.BooleanField(default=True, help_text='Send transport update notifications (bus departed, arriving, completed)'),
        ),
    ]
