# Generated by Django 5.2.11 on 2026-05-05 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_schoolnotificationconfig_attendance_reminder_flag'),
        ('schools', '0015_add_module_entitlements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnotificationconfig',
            name='absence_notification_enabled',
            field=models.BooleanField(default=True, help_text='Scheduled in-app absence digests (8–10 AM school time): staff see one message per class once attendance is complete; parents see their child only when absent.'),
        ),
        migrations.CreateModel(
            name='AttendanceAbsenceInAppDigestMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('digest_type', models.CharField(choices=[('staff_class', 'Staff class digest'), ('parent_student', 'Parent absent student')], max_length=32)),
                ('scope_key', models.CharField(help_text='Stable key: class cohort (class id + session id) or parent scope (student id)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_in_app_digest_markers', to='schools.school')),
            ],
            options={
                'verbose_name': 'Absence In-App Digest Marker',
                'verbose_name_plural': 'Absence In-App Digest Markers',
                'indexes': [models.Index(fields=['school', 'date', 'digest_type'], name='notificatio_school__a69536_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'date', 'digest_type', 'scope_key'), name='uniq_absence_in_app_digest_marker')],
            },
        ),
    ]
