# Generated by Django 5.2.11 on 2026-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_attendance_absence_in_app_digest_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolnotificationconfig',
            name='sms_enabled',
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolnotificationconfig',
            name='push_enabled',
            field=models.BooleanField(default=True, help_text='Deprecated: push delivery is now coupled with in-app notifications.'),
        ),
    ]
