# Generated by Django 5.2.11 on 2026-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_remove_sms_and_merge_push_with_inapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], max_length=20),
        ),
    ]
