# Generated by Django 5.2.11 on 2026-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notificationlog_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='assignment_due_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Remind students in-app when a published assignment is due soon and they have not submitted'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='attendance_risk_alert_enabled',
            field=models.BooleanField(default=True, help_text='Alert admins/principals (aggregate) and parents (per HIGH-risk child) from the nightly attendance risk snapshot'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='fee_overdue_grace_days',
            field=models.IntegerField(default=10, help_text='Days past month-end before an unpaid/partial fee counts as overdue (FeePayment has no per-payment due date)'),
        ),
        migrations.AddField(
            model_name='schoolnotificationconfig',
            name='library_due_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Remind borrowers (and parents, for student borrowers) when an issued library book is due soon or overdue'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('EXAM_SCHEDULE', 'Exam Schedule Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder'), ('ATTENDANCE_RISK', 'Attendance Risk Alert'), ('LEAVE_DECISION', 'Leave Request Decision')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('EXAM_SCHEDULE', 'Exam Schedule Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder'), ('ATTENDANCE_RISK', 'Attendance Risk Alert'), ('LEAVE_DECISION', 'Leave Request Decision')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ABSENCE', 'Absence Alert'), ('FEE_DUE', 'Fee Due Reminder'), ('FEE_OVERDUE', 'Fee Overdue Alert'), ('EXAM_RESULT', 'Exam Result Published'), ('EXAM_SCHEDULE', 'Exam Schedule Published'), ('GENERAL', 'General Announcement'), ('CUSTOM', 'Custom Message'), ('TRANSPORT_UPDATE', 'Transport Update'), ('LIBRARY_OVERDUE', 'Library Overdue Reminder'), ('ASSIGNMENT_DUE', 'Assignment Due Reminder'), ('ATTENDANCE_RISK', 'Attendance Risk Alert'), ('LEAVE_DECISION', 'Leave Request Decision')], max_length=20),
        ),
    ]
