# Generated by Django 5.2.11 on 2026-09-16 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_schoolnotificationconfig_assignment_due_reminder_enabled_and_more'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_user', 'channel', 'read_at'], name='notif_recipient_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_user', 'channel', '-created_at'], name='notif_recipient_feed_idx'),
        ),
    ]
