# Generated by Django 6.0.1 on 2026-02-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('academics', '0002_academicsaichatmessage'),
        ('schools', '0007_alter_userschoolmembership_role'),
        ('students', '0002_make_parent_phone_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('MARKS_ENTRY', 'Marks Entry'), ('COMPLETED', 'Completed'), ('PUBLISHED', 'Published')], default='SCHEDULED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic_sessions.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic_sessions.term')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=33.0, max_digits=6)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__name'],
                'unique_together': {('school', 'exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Weightage percentage for GPA calculation', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='examinations.examtype'),
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_label', models.CharField(help_text="e.g. 'A+', 'A', 'B'", max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_points', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='schools.school')),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Null means not entered yet', max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='examinations.examsubject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'ordering': ['student__roll_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'academic_year'], name='examination_school__b45529_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'class_obj'], name='examination_school__f363aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'exam_type', 'class_obj', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('school', 'grade_label')},
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'student'], name='examination_school__3939bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('school', 'exam_subject', 'student')},
        ),
    ]
