# Generated by Django 5.2.11 on 2026-02-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_session_scoped_roll_numbers'),
        ('academics', '0004_add_exam_group_model'),
        ('examinations', '0001_initial'),
        ('schools', '0011_alter_userschoolmembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examsubject',
            index=models.Index(fields=['exam', 'is_active'], name='examination_exam_id_5f69cc_idx'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups', to='academic_sessions.academicyear'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups', to='examinations.examtype'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups', to='schools.school'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups', to='academic_sessions.term'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='examinations.examgroup'),
        ),
        migrations.AddIndex(
            model_name='examgroup',
            index=models.Index(fields=['school', 'academic_year'], name='examination_school__e7a493_idx'),
        ),
        migrations.AddIndex(
            model_name='examgroup',
            index=models.Index(fields=['school', 'is_active'], name='examination_school__316f0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examgroup',
            unique_together={('school', 'name', 'academic_year')},
        ),
    ]
