# Generated by Django 5.2.11 on 2026-02-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_add_exam_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='ai_comment',
            field=models.TextField(blank=True, default='', help_text='AI-generated report card comment based on marks, grade, and attendance'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='ai_comment_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI comment was generated', null=True),
        ),
    ]
