# Generated by Django 5.2.11 on 2026-03-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_timetableslot_applicable_days'),
        ('examinations', '0003_studentmark_ai_comment_and_more'),
        ('schools', '0014_school_exam_config'),
        ('students', '0010_fix_class_name_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(help_text="e.g., 'Physics Mid-Term Exam 2026'", max_length=250)),
                ('instructions', models.TextField(blank=True, help_text='General instructions for students')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='students.class')),
                ('exam', models.ForeignKey(blank=True, help_text='Optional: Link to exam lifecycle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='examinations.exam')),
                ('exam_subject', models.ForeignKey(blank=True, help_text='Link to specific exam subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='examinations.examsubject')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Supabase storage URL', max_length=500)),
                ('ai_extracted_json', models.JSONField(blank=True, help_text='Structured questions extracted by AI', null=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Overall confidence score (0-100)', max_digits=5, null=True)),
                ('extraction_notes', models.TextField(blank=True, help_text='AI notes about extraction quality')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('REVIEWED', 'Reviewed'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('exam_paper', models.ForeignKey(blank=True, help_text='Linked after confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='examinations.exampaper')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_uploads', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_extracted_json', models.JSONField(help_text='Original AI extraction')),
                ('user_confirmed_json', models.JSONField(help_text="User's corrected version")),
                ('accuracy_metrics', models.JSONField(blank=True, help_text='Calculated accuracy scores', null=True)),
                ('correction_notes', models.TextField(blank=True, help_text='Optional notes about corrections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paper_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='examinations.paperupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text (supports HTML from rich editor)')),
                ('question_image_url', models.URLField(blank=True, help_text='Optional: URL for diagrams, charts, or images', max_length=500, null=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('ESSAY', 'Essay'), ('TRUE_FALSE', 'True/False'), ('MATCHING', 'Matching'), ('FILL_BLANK', 'Fill in the Blanks')], default='SHORT', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, help_text='Default marks for this question', max_digits=5)),
                ('option_a', models.TextField(blank=True, default='')),
                ('option_b', models.TextField(blank=True, default='')),
                ('option_c', models.TextField(blank=True, default='')),
                ('option_d', models.TextField(blank=True, default='')),
                ('correct_answer', models.CharField(blank=True, help_text='For MCQ: A/B/C/D. For others: answer key text', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(blank=True, help_text='Optional: Link to exam type (e.g., Mid-Term, Final)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='examinations.examtype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField(help_text='Display order in the paper (1, 2, 3...)')),
                ('marks_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override default marks for this specific paper', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='examinations.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_assignments', to='examinations.question')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.AddField(
            model_name='exampaper',
            name='questions',
            field=models.ManyToManyField(related_name='exam_papers', through='examinations.PaperQuestion', to='examinations.question'),
        ),
        migrations.AddIndex(
            model_name='paperupload',
            index=models.Index(fields=['school', 'status'], name='examination_school__13b5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paperupload',
            index=models.Index(fields=['uploaded_by', 'status'], name='examination_uploade_103be1_idx'),
        ),
        migrations.AddIndex(
            model_name='paperfeedback',
            index=models.Index(fields=['paper_upload'], name='examination_paper_u_82ee9f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school', 'subject'], name='examination_school__02b167_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school', 'is_active'], name='examination_school__b3f286_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='examination_difficu_daad22_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='examination_questio_4c64dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paperquestion',
            index=models.Index(fields=['exam_paper', 'question_order'], name='examination_exam_pa_a46f26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperquestion',
            unique_together={('exam_paper', 'question')},
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['school', 'class_obj'], name='examination_school__21aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['school', 'subject'], name='examination_school__844262_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['status'], name='examination_status_7b9704_idx'),
        ),
    ]
