# Generated by Django 5.2.11 on 2026-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_question_tested_topics_exampaper_lesson_plans'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='exam_q_school_active_idx',
        ),
    ]
