# Generated by Django 5.2.11 on 2026-03-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_remove_question_exam_q_school_active_idx'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the existing constraint
            'ALTER TABLE examinations_examsubject DROP CONSTRAINT examinations_examsub_exam_id_1f9d7189_fk_examinati;',
            # Recreate with CASCADE
            'ALTER TABLE examinations_examsubject ADD CONSTRAINT examinations_examsub_exam_id_1f9d7189_fk_examinati FOREIGN KEY (exam_id) REFERENCES examinations_exam(id) ON DELETE CASCADE;',
        ),
    ]
