# Generated by Django 5.2.11 on 2026-03-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_fix_cascade_sql'),
    ]

    operations = [        migrations.RunSQL(
            # Add the missing exam_id foreign key constraint with CASCADE
            'ALTER TABLE examinations_examsubject ADD CONSTRAINT examinations_examsub_exam_id_1f9d7189_fk_examinati FOREIGN KEY (exam_id) REFERENCES examinations_exam(id) ON DELETE CASCADE;',
            # Reverse operation: drop the constraint
            'ALTER TABLE examinations_examsubject DROP CONSTRAINT examinations_examsub_exam_id_1f9d7189_fk_examinati;',
        ),    ]
