# Generated by Django 5.2.11 on 2026-03-25 03:44

from django.db import migrations


CONSTRAINT_NAME = 'examinations_examsub_exam_id_1f9d7189_fk_examinati'


def add_exam_fk_cascade(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_constraint WHERE conname = %s",
            [CONSTRAINT_NAME],
        )
        if cursor.fetchone():
            return

    schema_editor.execute(
        'ALTER TABLE examinations_examsubject '
        f'ADD CONSTRAINT {CONSTRAINT_NAME} '
        'FOREIGN KEY (exam_id) REFERENCES examinations_exam(id) ON DELETE CASCADE;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_fix_cascade_sql'),
    ]

    operations = [
        migrations.RunPython(add_exam_fk_cascade, migrations.RunPython.noop),
    ]
