# Generated by Django 5.2.11 on 2026-03-25 03:45

from django.db import migrations


def fix_studentmark_cascade(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        'ALTER TABLE examinations_studentmark '
        'DROP CONSTRAINT examinations_student_exam_subject_id_9b755102_fk_examinati;'
    )
    schema_editor.execute(
        'ALTER TABLE examinations_studentmark '
        'ADD CONSTRAINT examinations_student_exam_subject_id_9b755102_fk_examinati '
        'FOREIGN KEY (exam_subject_id) REFERENCES examinations_examsubject(id) ON DELETE CASCADE;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0009_add_exam_fk_cascade'),
    ]

    operations = [
        migrations.RunPython(fix_studentmark_cascade, migrations.RunPython.noop),
    ]
