# Generated by Django 5.2.11 on 2026-03-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0009_add_exam_fk_cascade'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop and recreate StudentMark exam_subject constraint with CASCADE
            'ALTER TABLE examinations_studentmark DROP CONSTRAINT examinations_student_exam_subject_id_9b755102_fk_examinati;',
            'ALTER TABLE examinations_studentmark ADD CONSTRAINT examinations_student_exam_subject_id_9b755102_fk_examinati FOREIGN KEY (exam_subject_id) REFERENCES examinations_examsubject(id) ON DELETE CASCADE;',
        ),
    ]
