# Generated by Django 5.2.11 on 2026-03-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0011_studentmark_enrollment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentmark',
            new_name='examination_school__7f2cc2_idx',
            old_name='exm_sm_sch_enr_idx',
        ),
    ]
