# Generated by Django 5.2.11 on 2026-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0012_rename_exm_sm_sch_enr_idx_examination_school__7f2cc2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
