# Generated by Django 5.2.11 on 2026-04-15

from django.db import migrations, models
from django.db.models import F


def backfill_answer_text(apps, schema_editor):
    Question = apps.get_model('examinations', 'Question')
    Question.objects.filter(answer_text='', correct_answer__gt='').update(answer_text=F('correct_answer'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0013_add_examsubject_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('MCQ', 'Multiple Choice'),
                    ('SHORT', 'Short Answer'),
                    ('LONG', 'Long Answer'),
                    ('ESSAY', 'Essay'),
                    ('TRUE_FALSE', 'True/False'),
                    ('MATCHING', 'Matching'),
                    ('FILL_BLANK', 'Fill in the Blanks'),
                ],
                default='SHORT',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Long-form expected answer/model answer for subjective questions',
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='type_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Type-specific payload, e.g. matching pairs, blanks, rubrics',
            ),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(
                fields=['school', 'subject', 'question_type', 'difficulty_level'],
                name='examination_school__f77d58_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(
                fields=['school', 'subject', 'is_active'],
                name='examination_school__f87082_idx',
            ),
        ),
        migrations.RunPython(backfill_answer_text, reverse_code=noop_reverse),
    ]
