# Generated by Django 5.2.11 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0014_question_typed_payload_and_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(
                condition=models.Q(('exam_group__isnull', False)),
                fields=('school', 'exam_group', 'class_obj'),
                name='exam_group_class_unique',
            ),
        ),
    ]