# Generated by Django 6.0.4 on 2026-05-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0017_question_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20, null=True),
        ),
    ]
