# Generated by Django 6.0.4 on 2026-05-25 05:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0018_question_bloom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
