# Generated by Django 6.0.4 on 2026-05-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0020_questionrevision'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('avg_time_seconds', models.FloatField(blank=True, null=True)),
                ('real_difficulty', models.FloatField(blank=True, null=True)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='examinations.question')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='examinations.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='examinations.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['exam_paper', 'student'], name='examination_exam_pa_363c19_idx'), models.Index(fields=['question', 'submitted_at'], name='examination_questio_76f2d0_idx')],
                'unique_together': {('student', 'question', 'exam_paper')},
            },
        ),
    ]
