# Generated by Django 6.0.4 on 2026-05-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0021_questionstats_studentresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='last_used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_questions', to='examinations.exampaper'),
        ),
        migrations.AddField(
            model_name='question',
            name='paper_use_count',
            field=models.IntegerField(default=0),
        ),
    ]
