# Generated by Django 6.0.4 on 2026-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0022_question_last_used_at_question_last_used_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='render_options',
            field=models.JSONField(blank=True, default=dict, help_text='Paper render options (e.g., answer_lines).'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='structure',
            field=models.JSONField(blank=True, default=list, help_text='List of paper section dicts used for rendering/choices.'),
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='section_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
