# Generated by Django 6.0.4 on 2026-07-08 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('examinations', '0023_exampaper_render_options_exampaper_structure_and_more'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperupload',
            name='context_class',
            field=models.ForeignKey(blank=True, help_text="Uploader's optional class context; final selection always happens in the UI.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_uploads', to='students.class'),
        ),
        migrations.AddField(
            model_name='paperupload',
            name='context_subject',
            field=models.ForeignKey(blank=True, help_text="Uploader's optional subject context; final selection always happens in the UI.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_uploads', to='academics.subject'),
        ),
    ]
