# Generated by Django 6.0.4 on 2026-07-10 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0013_schoolcalendarentry_affects_staff_affects_students'),
        ('examinations', '0024_paperupload_context_class_and_more'),
        ('schools', '0016_alter_school_module_entitlements'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('speaking', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('writing', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('reading', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('participation', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('confidence', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('social_skills', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('discipline', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('respect', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('teamwork', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('class_participation', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('responsibility', models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('teacher_remark', models.TextField(blank=True)),
                ('principal_remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_term_assessments', to='academic_sessions.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_term_assessments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_assessments', to='students.student')),
                ('term', models.ForeignKey(blank=True, help_text='Optional finer scope; left blank for a whole-year assessment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_term_assessments', to='academic_sessions.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Term Assessment',
                'verbose_name_plural': 'Student Term Assessments',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
    ]
