# Generated by Django 5.2.11 on 2026-09-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0027_studenttermassessment_month_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='schedule_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
