# Generated by Django 5.2.11 on 2026-09-08 06:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0028_exam_schedule_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperfeedback',
            name='accuracy_metrics',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Calculated accuracy scores', null=True),
        ),
        migrations.AlterField(
            model_name='paperfeedback',
            name='ai_extracted_json',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Original AI extraction'),
        ),
        migrations.AlterField(
            model_name='paperfeedback',
            name='user_confirmed_json',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="User's corrected version"),
        ),
    ]
