# Generated by Django 5.2.11 on 2026-09-09 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('examinations', '0029_paper_feedback_json_encoder'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paperupload',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Ties sequential pages of one multi-page paper capture together. Null for a standalone single-page upload (all pre-multi-page rows, and any single-page capture going forward).', null=True),
        ),
        migrations.AddField(
            model_name='paperupload',
            name='page_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-based page order within group_id. Meaningless when group_id is null.'),
        ),
        migrations.AddIndex(
            model_name='paperupload',
            index=models.Index(fields=['group_id', 'page_number'], name='examination_group_i_4ed7f4_idx'),
        ),
    ]
