# Generated by Django 5.2.11 on 2026-09-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0030_paperupload_group_id_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
