# Generated by Django 5.2.11 on 2026-09-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('examinations', '0031_add_question_diagram_image_fields'),
        ('lms', '0018_backfill_class2_section_a_lesson_plans'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Fractions Practice Sheet'", max_length=250)),
                ('instructions', models.TextField(blank=True, help_text='General instructions for students')),
                ('structure', models.JSONField(blank=True, default=list, help_text='List of section dicts -- same shape as ExamPaper.structure, so paper_export_layout.py renders both without duplicating that logic.')),
                ('render_options', models.JSONField(blank=True, default=dict, help_text='Render options (e.g., answer_lines).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SCAN', 'Image Scan'), ('BANK', 'Question Bank')], default='MANUAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='students.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worksheets', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='schools.school')),
                ('subject', models.ForeignKey(blank=True, help_text='Optional: some worksheets (e.g. general revision) span subjects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='academics.subject')),
                ('tested_topics', models.ManyToManyField(blank=True, help_text='Curriculum topics this worksheet practises', related_name='worksheets', to='lms.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.PositiveIntegerField(help_text='Display order on the worksheet (1, 2, 3...)')),
                ('section_key', models.CharField(blank=True, default='', max_length=50)),
                ('marks_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional -- worksheets are usually ungraded, but a teacher may still mark homework', max_digits=5, null=True)),
                ('item_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen copy of the question at the time it was attached or saved into the worksheet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_assignments', to='examinations.question')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='examinations.worksheet')),
            ],
            options={
                'ordering': ['item_order'],
            },
        ),
        migrations.AddField(
            model_name='worksheet',
            name='questions',
            field=models.ManyToManyField(related_name='worksheets', through='examinations.WorksheetItem', to='examinations.question'),
        ),
        migrations.CreateModel(
            name='WorksheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Supabase storage URL', max_length=500)),
                ('group_id', models.UUIDField(blank=True, db_index=True, help_text='Ties sequential pages of one multi-page worksheet capture together.', null=True)),
                ('page_number', models.PositiveSmallIntegerField(default=1, help_text='1-based page order within group_id. Meaningless when group_id is null.')),
                ('ai_extracted_json', models.JSONField(blank=True, help_text='Structured questions extracted by AI', null=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extraction_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('REVIEWED', 'Reviewed'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('context_class', models.ForeignKey(blank=True, help_text="Uploader's optional class context; final selection always happens in the UI.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_uploads', to='students.class')),
                ('context_subject', models.ForeignKey(blank=True, help_text="Uploader's optional subject context; final selection always happens in the UI.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_uploads', to='academics.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_uploads', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_uploads', to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(blank=True, help_text='Linked after confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='examinations.worksheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worksheetitem',
            index=models.Index(fields=['worksheet', 'item_order'], name='examination_workshe_27fbbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worksheetitem',
            unique_together={('worksheet', 'question')},
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['school', 'class_obj'], name='examination_school__003893_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['school', 'subject'], name='examination_school__b7e504_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheet',
            index=models.Index(fields=['status'], name='examination_status_8672c5_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetupload',
            index=models.Index(fields=['school', 'status'], name='examination_school__55eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetupload',
            index=models.Index(fields=['uploaded_by', 'status'], name='examination_uploade_a210d9_idx'),
        ),
        migrations.AddIndex(
            model_name='worksheetupload',
            index=models.Index(fields=['group_id', 'page_number'], name='examination_group_i_7ad6ea_idx'),
        ),
    ]
