# Generated by Django 5.2.11 on 2026-09-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0032_add_worksheets'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='ai_comment_source',
            field=models.CharField(blank=True, help_text='AI / FALLBACK / EDITED; EDITED comments are never overwritten by regeneration', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentExamComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('AI', 'AI'), ('FALLBACK', 'Template'), ('EDITED', 'Edited')], default='AI', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_comments', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_comments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_comments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'exam'], name='examination_school__222451_idx')],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
