# Generated by Django 5.2.11 on 2026-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0033_add_comment_source_and_exam_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamcomment',
            name='ai_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Model that wrote the comment (blank for template/edited comments)', max_length=60, null=True),
        ),
    ]
