# Generated by Django 5.2.11 on 2026-09-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0035_report_card_promotion_override'),
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcardoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportcardoverride',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_overrides', to='examinations.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcardoverride',
            unique_together={('student', 'exam')},
        ),
    ]
