# Generated by Django 5.2.11 on 2026-09-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_studentenrollment_left_date'),
        ('examinations', '0037_attach_report_card_overrides_to_exam'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_group_class_unique',
        ),
        migrations.AddField(
            model_name='exam',
            name='session_class',
            field=models.ForeignKey(blank=True, help_text='Set for a section-only exam. Null = every section of class_obj.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic_sessions.sessionclass'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_group__isnull', False), ('session_class__isnull', True)), fields=('school', 'exam_group', 'class_obj'), name='exam_group_class_unique'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('exam_group__isnull', False), ('session_class__isnull', False)), fields=('school', 'exam_group', 'session_class'), name='exam_group_section_unique'),
        ),
    ]
