# Generated by Django 5.2.11 on 2026-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0038_exam_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='fail_threshold_subjects',
            field=models.PositiveSmallIntegerField(default=3, help_text='Fail overall if this many subjects (or more) are failed.'),
        ),
    ]
