# Generated by Django 5.2.11 on 2026-02-18 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0002_session_scoped_roll_numbers'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0009_session_scoped_roll_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('NEEDS_REVIEW', 'Needs Review'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('total_faces_detected', models.PositiveIntegerField(default=0)),
                ('faces_matched', models.PositiveIntegerField(default=0)),
                ('faces_flagged', models.PositiveIntegerField(default=0)),
                ('faces_ignored', models.PositiveIntegerField(default=0)),
                ('thresholds_used', models.JSONField(blank=True, default=dict, help_text='Thresholds at processing time: {"high": 0.40, "medium": 0.55}')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_attendance_sessions', to='academic_sessions.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance_sessions', to='students.class', verbose_name='Class')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_sessions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance_sessions', to='schools.school')),
            ],
            options={
                'verbose_name': 'Face Attendance Session',
                'verbose_name_plural': 'Face Attendance Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_index', models.PositiveIntegerField(help_text='Order of face in the image (0-based)')),
                ('bounding_box', models.JSONField(help_text='{"top": y, "right": x, "bottom": y, "left": x}')),
                ('face_crop_url', models.URLField(blank=True, help_text='URL of cropped face image in Supabase', max_length=500)),
                ('quality_score', models.FloatField(default=0, help_text='Face quality score 0-1')),
                ('embedding', models.BinaryField(blank=True, help_text='128-d embedding stored for debugging/reprocessing', null=True)),
                ('confidence', models.FloatField(default=0, help_text='Match confidence 0-100 percentage')),
                ('match_status', models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched (High Confidence)'), ('FLAGGED', 'Flagged (Medium Confidence)'), ('IGNORED', 'Ignored (Low Confidence)'), ('MANUALLY_MATCHED', 'Manually Matched'), ('REMOVED', 'Removed by Teacher')], default='IGNORED', max_length=20)),
                ('match_distance', models.FloatField(blank=True, help_text='Raw L2 distance from face_recognition (lower = better match)', null=True)),
                ('alternative_matches', models.JSONField(blank=True, default=list, help_text='[{"student_id": 5, "name": "...", "confidence": 72.1, "distance": 0.38}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_detections', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='face_attendance.faceattendancesession')),
            ],
            options={
                'verbose_name': 'Face Detection Result',
                'verbose_name_plural': 'Face Detection Results',
                'ordering': ['session', 'face_index'],
            },
        ),
        migrations.CreateModel(
            name='StudentFaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='128-dimensional float64 numpy array stored as bytes')),
                ('embedding_version', models.CharField(default='dlib_v1', help_text='Model version used to generate this embedding', max_length=20)),
                ('source_image_url', models.URLField(blank=True, help_text='Original photo used for enrollment', max_length=500)),
                ('quality_score', models.FloatField(default=0, help_text='Face quality score 0-1 (size, blur, lighting)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(help_text='Denormalized for fast class-scoped queries', on_delete=django.db.models.deletion.CASCADE, related_name='student_face_embeddings', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Face Embedding',
                'verbose_name_plural': 'Student Face Embeddings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faceattendancesession',
            index=models.Index(fields=['school', 'class_obj', 'date'], name='face_attend_school__f3f073_idx'),
        ),
        migrations.AddIndex(
            model_name='faceattendancesession',
            index=models.Index(fields=['status'], name='face_attend_status_49635f_idx'),
        ),
        migrations.AddIndex(
            model_name='faceattendancesession',
            index=models.Index(fields=['-created_at'], name='face_attend_created_e9d900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facedetectionresult',
            unique_together={('session', 'face_index')},
        ),
        migrations.AddIndex(
            model_name='studentfaceembedding',
            index=models.Index(fields=['school', 'is_active'], name='face_attend_school__42abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfaceembedding',
            index=models.Index(fields=['student', 'is_active'], name='face_attend_student_36b62c_idx'),
        ),
    ]
