# Generated by Django 6.0.4 on 2026-07-28 07:47

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfaceembedding',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True),
        ),
        migrations.AlterField(
            model_name='studentfaceembedding',
            name='embedding',
            field=models.BinaryField(help_text='128-dimensional float64 numpy array stored as bytes (legacy, see embedding_vector)'),
        ),
    ]
