# Generated by Django 6.0.4 on 2026-07-28 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_add_leave_status'),
        ('face_attendance', '0003_backfill_embedding_vector'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttendanceSchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_a_enabled', models.BooleanField(default=False, help_text='Mobile-browser live capture (not implemented yet)')),
                ('tier_b_enabled', models.BooleanField(default=False, help_text='Fixed on-prem camera live capture')),
                ('tier_c_enabled', models.BooleanField(default=True, help_text='Group-photo capture + review (the original flow)')),
                ('live_window_start', models.TimeField(blank=True, help_text='Arrival window start for live tiers (semantics not yet enforced)', null=True)),
                ('live_window_end', models.TimeField(blank=True, help_text='Arrival window end for live tiers (semantics not yet enforced)', null=True)),
                ('threshold_overrides', models.JSONField(blank=True, help_text='Optional per-embedding-version threshold overrides (not yet consulted by matching)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Face Attendance School Config',
                'verbose_name_plural': 'Face Attendance School Configs',
            },
        ),
        migrations.CreateModel(
            name='FaceCaptureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Front Gate Camera"', max_length=100)),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_key_hash', models.CharField(editable=False, help_text='SHA-256 hex digest of the device API key. The raw key is shown once at creation and never stored.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding_version', models.CharField(default='dlib_v1', help_text='Fixed per device — a device always emits vectors from one embedding space', max_length=20)),
                ('scope_type', models.CharField(choices=[('CLASS', 'Single Class'), ('SCHOOL', 'Whole School')], max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(blank=True, help_text='Required when scope_type=CLASS, must be null when scope_type=SCHOOL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_capture_devices', to='students.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_capture_devices_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_capture_devices', to='schools.school')),
            ],
            options={
                'verbose_name': 'Face Capture Device',
                'verbose_name_plural': 'Face Capture Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceLiveDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_tier', models.CharField(choices=[('TIER_A', 'Mobile Browser'), ('TIER_B', 'Fixed Camera')], max_length=10)),
                ('embedding_version', models.CharField(max_length=20)),
                ('client_timestamp', models.DateTimeField(help_text='Capture-side clock, as reported by the device/browser')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0, help_text='Match confidence 0-100 percentage')),
                ('distance', models.FloatField(blank=True, help_text='Raw L2 distance (lower = better match)', null=True)),
                ('match_status', models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched (High Confidence)'), ('FLAGGED', 'Flagged (Medium Confidence)'), ('IGNORED', 'Ignored (Low Confidence)')], max_length=20)),
                ('resulted_in_attendance', models.BooleanField(default=False, help_text='True only for the first AUTO_MATCHED event per (student, date) that wrote the AttendanceRecord')),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events', to='attendance.attendancerecord')),
                ('captured_by', models.ForeignKey(blank=True, help_text='Set for Tier A events (not populated yet — Tier A is not implemented)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events_captured', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(blank=True, help_text='Set when the source device is CLASS-scoped; null for SCHOOL-scoped devices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events', to='students.class', verbose_name='Class')),
                ('device', models.ForeignKey(blank=True, help_text='Set for Tier B events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='face_attendance.facecapturedevice')),
                ('matched_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events', to='students.student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_live_detection_events', to='schools.school')),
            ],
            options={
                'verbose_name': 'Face Live Detection Event',
                'verbose_name_plural': 'Face Live Detection Events',
                'ordering': ['-client_timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='facecapturedevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('class_obj__isnull', False), ('scope_type', 'CLASS')), models.Q(('class_obj__isnull', True), ('scope_type', 'SCHOOL')), _connector='OR'), name='face_capture_device_scope_consistency'),
        ),
        migrations.AddIndex(
            model_name='facelivedetectionevent',
            index=models.Index(fields=['school', 'class_obj', 'client_timestamp'], name='face_attend_school__4c53d7_idx'),
        ),
        migrations.AddIndex(
            model_name='facelivedetectionevent',
            index=models.Index(fields=['school', 'matched_student', 'client_timestamp'], name='face_attend_school__45347b_idx'),
        ),
        migrations.AddIndex(
            model_name='facelivedetectionevent',
            index=models.Index(fields=['match_status'], name='face_attend_match_s_24b61a_idx'),
        ),
    ]
