# Generated by Django 6.0.4 on 2026-07-28 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0005_backfill_school_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facelivedetectionevent',
            name='captured_by',
            field=models.ForeignKey(blank=True, help_text='Set for Tier A events — the teacher/guard whose session posted the embedding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events_captured', to=settings.AUTH_USER_MODEL),
        ),
    ]
