# Generated by Django 6.0.4 on 2026-07-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0006_alter_facelivedetectionevent_captured_by'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMatchThresholdSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tier', models.CharField(choices=[('TIER_A', 'Mobile Browser'), ('TIER_B', 'Fixed Camera')], max_length=10)),
                ('embedding_version', models.CharField(max_length=20)),
                ('distance', models.FloatField(help_text='Raw L2 distance the system matched on')),
                ('predicted_match_status', models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched (High Confidence)'), ('FLAGGED', 'Flagged (Medium Confidence)')], max_length=20)),
                ('is_correct', models.BooleanField(help_text="Operator's label: was the predicted match actually correct?")),
                ('sample_date', models.DateField(help_text='Date the sample was captured (coarse on purpose)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_match_threshold_samples', to='schools.school')),
            ],
            options={
                'verbose_name': 'Face Match Threshold Sample',
                'verbose_name_plural': 'Face Match Threshold Samples',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['embedding_version', 'predicted_match_status'], name='face_attend_embeddi_acf14c_idx')],
            },
        ),
    ]
