# Generated by Django 6.0.4 on 2026-07-31 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0010_migrate_source_method_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceattendanceschoolconfig',
            name='live_window_end',
            field=models.TimeField(blank=True, help_text='Arrival window end for live capture methods (semantics not yet enforced)', null=True),
        ),
        migrations.AlterField(
            model_name='faceattendanceschoolconfig',
            name='live_window_start',
            field=models.TimeField(blank=True, help_text='Arrival window start for live capture methods (semantics not yet enforced)', null=True),
        ),
        migrations.AlterField(
            model_name='facelivedetectionevent',
            name='captured_by',
            field=models.ForeignKey(blank=True, help_text='Set for Live Mobile capture events — the teacher/guard whose session posted the embedding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_live_detection_events_captured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facelivedetectionevent',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Set for Fixed Camera capture events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='face_attendance.facecapturedevice'),
        ),
    ]
