# Generated by Django 6.0.4 on 2026-08-01 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_attendance', '0011_alter_help_text_wording'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment'), ('RE_ENROLLMENT', 'Re-enrollment'), ('ATTENDANCE_MATCH', 'Attendance Match'), ('ADMIN_OVERRIDE', 'Admin Override/Reassignment')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event-specific detail — confidence/distance, session/detection ids, from/to student on overrides.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin/teacher who performed the action. Null for device-sourced Fixed Camera events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_audit_logs', to='schools.school')),
                ('student', models.ForeignKey(blank=True, help_text='Subject of the event. Null for batch-level events (e.g. a whole session confirm).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_audit_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Face Audit Log',
                'verbose_name_plural': 'Face Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'event_type', '-created_at'], name='face_attend_school__30dd62_idx'), models.Index(fields=['school', 'student', '-created_at'], name='face_attend_school__9f9650_idx')],
            },
        ),
    ]
