"""
Letter PDF generator — renders custom letters on school letterhead.
Uses reportlab canvas for precise positioning with letterhead background.
"""

import io
import re
import logging
from datetime import datetime

import httpx
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger(__name__)

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 50
TOP_SPACE = 144  # Space reserved for letterhead header area
FOOTER_SPACE = 50
BODY_TOP_MARGIN = TOP_SPACE + 60


class LetterPDFGenerator:
    """Generates a PDF letter with school letterhead background."""

    def __init__(self, school, recipient, subject, body_text,
                 line_spacing='single', admin_name='Admin'):
        self.school = school
        self.recipient = recipient
        self.subject = subject
        self.body_text = body_text
        self.line_spacing = line_spacing
        self.admin_name = admin_name

        self.font_regular = 'Helvetica'
        self.font_bold = 'Helvetica-Bold'
        self.font_italic = 'Helvetica-Oblique'
        self.font_mono = 'Courier'
        self.font_size = 12
        self.line_height = self._calc_line_height()

        self._letterhead_image = None

    def _calc_line_height(self):
        base = self.font_size + 5
        if self.line_spacing == '1.5':
            base = self.font_size + 8
        elif self.line_spacing == 'double':
            base = self.font_size + 12
        return base

    def _fetch_letterhead(self):
        """Download letterhead image from school's Supabase URL."""
        url = getattr(self.school, 'letterhead_url', None)
        if not url:
            logger.info("No letterhead_url for school %s, using white background", self.school.id)
            return None
        try:
            resp = httpx.get(url, timeout=15, follow_redirects=True)
            resp.raise_for_status()
            return ImageReader(io.BytesIO(resp.content))
        except Exception as e:
            logger.warning("Failed to fetch letterhead for school %s: %s", self.school.id, e)
            return None

    def _draw_background(self, c):
        """Draw letterhead image as full-page background, or white fallback."""
        if self._letterhead_image:
            try:
                c.drawImage(
                    self._letterhead_image, 0, 0,
                    width=PAGE_WIDTH, height=PAGE_HEIGHT,
                    preserveAspectRatio=False, mask='auto',
                )
                return
            except Exception as e:
                logger.warning("Error drawing letterhead: %s", e)
        # Fallback: white page
        c.setFillColorRGB(1, 1, 1)
        c.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=True, stroke=False)

    def _draw_footer(self, c):
        """Draw footer text centered at bottom."""
        footer = f"---This document is generated by Admin: {self.admin_name}------"
        c.setFont(self.font_regular, 10)
        c.setFillColorRGB(0, 0, 0)
        tw = pdfmetrics.stringWidth(footer, self.font_regular, 10)
        c.drawString((PAGE_WIDTH - tw) / 2, MARGIN, footer)

    def _draw_header_info(self, c):
        """Draw address and date in top-right area (below letterhead header)."""
        headers = [
            f"Date: {datetime.now().strftime('%A, %B %d, %Y')}",
        ]
        y = PAGE_HEIGHT - MARGIN
        c.setFont(self.font_regular, 10)
        c.setFillColorRGB(0, 0, 0)
        max_w = 200
        for line in headers:
            c.drawString(PAGE_WIDTH - MARGIN - max_w, y, line)
            y -= 16

    def _wrap_text(self, text, font, size, max_width):
        """Word-wrap text into lines that fit within max_width."""
        words = text.split()
        lines = []
        current = ''
        for word in words:
            test = f"{current} {word}".strip() if current else word
            if pdfmetrics.stringWidth(test, font, size) > max_width and current:
                lines.append(current)
                current = word
            else:
                current = test
        if current:
            lines.append(current)
        return lines

    def _new_page(self, c):
        """Start a new page with background and return top Y position."""
        c.showPage()
        self._draw_background(c)
        return PAGE_HEIGHT - BODY_TOP_MARGIN

    def _check_page_break(self, c, y, needed=None):
        """If y is too low, start a new page. Returns new y."""
        needed = needed or self.line_height
        if y < MARGIN + FOOTER_SPACE + needed:
            self._draw_footer(c)
            return self._new_page(c)
        return y

    def _parse_text_runs(self, text):
        """Parse simple markup into font runs: *bold*, _italic_, ~strike~, ```mono```."""
        pattern = r'(\*[^*]+\*|_[^_]+_|~[^~]+~|```[^`]+```)'
        parts = re.split(pattern, text)
        runs = []
        for part in parts:
            if not part:
                continue
            if part.startswith('*') and part.endswith('*'):
                runs.append({'text': part[1:-1], 'font': self.font_bold, 'strike': False})
            elif part.startswith('_') and part.endswith('_'):
                runs.append({'text': part[1:-1], 'font': self.font_italic, 'strike': False})
            elif part.startswith('~') and part.endswith('~'):
                runs.append({'text': part[1:-1], 'font': self.font_regular, 'strike': True})
            elif part.startswith('```') and part.endswith('```'):
                runs.append({'text': part[3:-3], 'font': self.font_mono, 'strike': False})
            else:
                runs.append({'text': part, 'font': self.font_regular, 'strike': False})
        return runs

    def _draw_runs(self, c, x_start, y, runs, max_width):
        """Draw text runs with word wrapping and page breaks. Returns (new_y, canvas)."""
        current_x = x_start
        for run in runs:
            words = run['text'].split()
            for word in words:
                w = pdfmetrics.stringWidth(word + ' ', run['font'], self.font_size)
                # Wrap to next line if needed
                if current_x + w > x_start + max_width and current_x > x_start:
                    y -= self.line_height
                    y = self._check_page_break(c, y)
                    current_x = x_start

                c.setFont(run['font'], self.font_size)
                c.setFillColorRGB(0, 0, 0)
                c.drawString(current_x, y, word)

                if run['strike']:
                    word_w = pdfmetrics.stringWidth(word, run['font'], self.font_size)
                    c.line(current_x, y + self.font_size / 3,
                           current_x + word_w, y + self.font_size / 3)

                current_x += w
        return y - self.line_height

    def generate(self):
        """Generate the letter PDF and return bytes."""
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)

        # Pre-fetch letterhead once
        self._letterhead_image = self._fetch_letterhead()

        # Page 1
        self._draw_background(c)
        self._draw_header_info(c)

        y = PAGE_HEIGHT - TOP_SPACE - 20

        # --- To field ---
        c.setFont(self.font_bold, self.font_size)
        c.setFillColorRGB(0, 0, 0)
        c.drawString(MARGIN, y, "To:")
        label_w = pdfmetrics.stringWidth("To: ", self.font_bold, self.font_size)
        to_max_width = PAGE_WIDTH - 2 * MARGIN - label_w
        to_line_height = self.font_size + 4

        first_line = True
        for raw_line in self.recipient.split('\n'):
            wrapped = self._wrap_text(raw_line, self.font_regular, self.font_size, to_max_width)
            for wl in wrapped:
                if not first_line:
                    y -= to_line_height
                c.setFont(self.font_regular, self.font_size)
                c.drawString(MARGIN + label_w, y, wl)
                first_line = False

        # --- Subject field ---
        y -= to_line_height + 5
        c.setFont(self.font_bold, self.font_size)
        c.drawString(MARGIN, y, "Subject: ")
        subj_label_w = pdfmetrics.stringWidth("Subject: ", self.font_bold, self.font_size)
        subj_max_width = PAGE_WIDTH - 2 * MARGIN - subj_label_w

        first_line = True
        for wl in self._wrap_text(self.subject, self.font_regular, self.font_size, subj_max_width):
            if not first_line:
                y -= to_line_height
            c.setFont(self.font_regular, self.font_size)
            c.drawString(MARGIN + subj_label_w, y, wl)
            first_line = False

        # --- Body ---
        y -= self.line_height + 15
        list_indent = 30
        content_width = PAGE_WIDTH - 2 * MARGIN

        for line in self.body_text.split('\n'):
            y = self._check_page_break(c, y)

            if not line.strip():
                y -= self.line_height
                continue

            # Check for numbered list
            num_match = re.match(r'^\s*(\d+)\.\s+(.*)$', line)
            bullet_match = re.match(r'^\s*[-*]\s+(.*)$', line)

            if num_match:
                number = num_match.group(1)
                item_text = num_match.group(2)
                c.setFont(self.font_regular, self.font_size)
                c.drawString(MARGIN, y, f"{number}. ")
                runs = self._parse_text_runs(item_text)
                y = self._draw_runs(c, MARGIN + list_indent, y, runs,
                                    content_width - list_indent)
            elif bullet_match:
                item_text = bullet_match.group(1)
                c.setFont(self.font_regular, self.font_size)
                c.drawString(MARGIN, y, "\u2022")
                runs = self._parse_text_runs(item_text)
                y = self._draw_runs(c, MARGIN + list_indent, y, runs,
                                    content_width - list_indent)
            else:
                runs = self._parse_text_runs(line)
                y = self._draw_runs(c, MARGIN, y, runs, content_width)

        # --- Signature ---
        y = self._check_page_break(c, y, needed=self.line_height * 3)
        y -= 30
        c.setFont(self.font_bold, self.font_size)
        c.drawString(MARGIN, y, "Regards,")
        y -= self.line_height
        c.setFont(self.font_regular, self.font_size)
        c.drawString(MARGIN, y, self.school.name)

        # Footer on last page
        self._draw_footer(c)

        c.save()
        return buffer.getvalue()
