# Generated by Django 6.0.1 on 2026-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.CharField(help_text="Unique subdomain for the school (e.g., 'focus' for focus.smartattendance.com)", max_length=50, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_sender_id', models.CharField(blank=True, help_text='WhatsApp Business API sender ID for this school', max_length=100)),
                ('enabled_modules', models.JSONField(default=dict, help_text="Feature flags: {'attendance_ai': true, 'whatsapp': true}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
