# Generated by Django 6.0.1 on 2026-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_register_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subdomain',
            field=models.CharField(help_text="Unique subdomain for the school (e.g., 'focus' for focus.kodereduai.pk)", max_length=50, unique=True),
        ),
    ]
