# Generated by Django 6.0.1 on 2026-02-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_populate_org_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschoolmembership',
            name='role',
            field=models.CharField(choices=[('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
