# Generated by Django 6.0.1 on 2026-02-13 04:41

import core.module_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_userschoolmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_modules',
            field=models.JSONField(default=core.module_registry.get_default_modules, help_text='Module ceiling for this org. Schools can only enable modules allowed here.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='enabled_modules',
            field=models.JSONField(default=core.module_registry.get_default_modules, help_text="Per-school module toggles: {'attendance': true, 'finance': true, ...}"),
        ),
    ]
