# Generated by Django 6.0.1 on 2026-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_populate_module_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschoolmembership',
            name='role',
            field=models.CharField(choices=[('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('HR_MANAGER', 'HR Manager'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('PARENT', 'Parent')], default='STAFF', max_length=20),
        ),
    ]
