# Generated by Django 5.2.11 on 2026-02-21 00:28

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ai_config',
            field=models.JSONField(blank=True, default=schools.models.default_ai_config, help_text='Per-school AI pipeline config: thresholds, providers, auto-tune settings'),
        ),
    ]
