# Generated by Django 5.2.11 on 2026-02-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_ai_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='letterhead_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
