# Generated by Django 5.2.11 on 2026-02-24 11:57

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_school_letterhead_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='exam_config',
            field=models.JSONField(blank=True, default=schools.models.default_exam_config, help_text='Per-school exam config: weighted average toggle, etc.'),
        ),
    ]
