# Generated by Django 5.2.11 on 2026-04-25 10:34

import core.module_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_school_exam_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='module_entitlements',
            field=models.JSONField(blank=True, default=core.module_registry.get_default_entitlements, help_text="Per-school capability lists: {'attendance': ['manual_entry', 'ocr_review'], ...}"),
        ),
    ]
