# Generated by Django 5.2.11 on 2026-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_module_entitlements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='module_entitlements',
            field=models.JSONField(blank=True, default=dict, help_text='DEPRECATED: Per-school capability lists. No longer used as a commercial gate.'),
        ),
    ]
