# Generated by Django 6.0.4 on 2026-07-28 05:54

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_alter_school_module_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_config',
            field=models.JSONField(blank=True, default=schools.models.default_attendance_config, help_text='Per-school attendance config: AI risk threshold, etc.'),
        ),
    ]
