# Generated by Django 6.0.4 on 2026-07-28 07:07

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_attendance_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_risk_config',
            field=models.JSONField(blank=True, default=schools.models.default_academic_risk_config, help_text='Per-school academic risk config: AI pass-rate threshold, etc.'),
        ),
        migrations.AddField(
            model_name='school',
            name='inventory_config',
            field=models.JSONField(blank=True, default=schools.models.default_inventory_config, help_text='Per-school inventory config: AI reorder lookahead window, etc.'),
        ),
    ]
