# Generated by Django 6.0.1 on 2026-02-12 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0007_alter_userschoolmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('MATERNITY', 'Maternity Leave'), ('UNPAID', 'Unpaid Leave'), ('OTHER', 'Other')], max_length=20)),
                ('days_allowed', models.IntegerField(help_text='Total allowed days per year')),
                ('carry_forward', models.BooleanField(default=False, help_text='Allow unused days to carry forward')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='schools.school')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_departments', to='schools.school')),
            ],
            options={
                'verbose_name': 'Staff Department',
                'verbose_name_plural': 'Staff Departments',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='hr.staffdepartment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_designations', to='schools.school')),
            ],
            options={
                'verbose_name': 'Staff Designation',
                'verbose_name_plural': 'Staff Designations',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='School-assigned employee ID', max_length=50)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hr.staffdepartment')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hr.staffdesignation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school')),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account (null if staff has no login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_DOCUMENT', 'ID Document'), ('CONTRACT', 'Contract'), ('CERTIFICATE', 'Certificate'), ('MEDICAL', 'Medical Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField(help_text='Supabase storage URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_records', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.JSONField(default=dict, help_text='e.g. {"house_rent": 10000, "transport": 2000}')),
                ('deductions', models.JSONField(default=dict, help_text='e.g. {"provident_fund": 2000, "tax": 3500}')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('rating', models.IntegerField(help_text='Overall rating 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_appraisals', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Performance Appraisal',
                'verbose_name_plural': 'Performance Appraisals',
                'ordering': ['-review_period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g. 2026)')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances_breakdown', models.JSONField(default=dict)),
                ('deductions_breakdown', models.JSONField(default=dict)),
                ('working_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='schools.school')),
                ('leave_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hr.leavepolicy')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATION', 'Certification'), ('TRAINING', 'Training'), ('LICENSE', 'License')], default='DEGREE', max_length=20)),
                ('qualification_name', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('year_of_completion', models.IntegerField(blank=True, null=True)),
                ('grade_or_percentage', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_qualifications', to='schools.school')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='hr.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Qualification',
                'verbose_name_plural': 'Staff Qualifications',
                'ordering': ['-year_of_completion'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['school', 'is_active'], name='hr_staffmem_school__899e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['school', 'employment_status'], name='hr_staffmem_school__a913ea_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['school', 'department'], name='hr_staffmem_school__ecd6e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffmember',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__gt', '')), fields=('school', 'employee_id'), name='unique_employee_id_per_school'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['school', 'date'], name='hr_staffatt_school__06c366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('school', 'staff_member', 'date')},
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['school', 'staff_member'], name='hr_salaryst_school__3e179b_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['school', 'year', 'month'], name='hr_payslip_school__39e6ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('school', 'staff_member', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['school', 'status'], name='hr_leaveapp_school__e8dc61_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['staff_member', 'start_date', 'end_date'], name='hr_leaveapp_staff_m_3a91fd_idx'),
        ),
    ]
