# Generated by Django 6.0.4 on 2026-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
