# Generated by Django 5.2.11 on 2026-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_fix_stuck_inactive_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional expiry date (contract end, ID/medical cert renewal, etc.)', null=True),
        ),
    ]
