# Generated by Django 6.0.1 on 2026-02-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('schools', '0010_alter_userschoolmembership_role'),
        ('students', '0004_student_address_student_admission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField(blank=True, null=True)),
                ('child_gender', models.CharField(blank=True, default='', max_length=10)),
                ('previous_school', models.CharField(blank=True, default='', max_length=200)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('parent_occupation', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('PHONE', 'Phone Call'), ('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Social Media'), ('AD_CAMPAIGN', 'Ad Campaign'), ('OTHER', 'Other')], default='WALK_IN', max_length=30)),
                ('referral_details', models.CharField(blank=True, default='', max_length=200)),
                ('stage', models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('VISIT_SCHEDULED', 'Campus Visit Scheduled'), ('VISIT_DONE', 'Campus Visit Done'), ('FORM_SUBMITTED', 'Application Submitted'), ('TEST_SCHEDULED', 'Test Scheduled'), ('TEST_DONE', 'Test Completed'), ('OFFERED', 'Offer Made'), ('ACCEPTED', 'Accepted'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_for_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_enquiries', to='students.grade')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('converted_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_enquiry', to='students.student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_enquiries', to='schools.school')),
            ],
            options={
                'verbose_name': 'Admission Enquiry',
                'verbose_name_plural': 'Admission Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PHOTO', 'Passport Photo'), ('BIRTH_CERT', 'Birth Certificate'), ('PREV_REPORT', 'Previous Report Card'), ('TC', 'Transfer Certificate'), ('MEDICAL', 'Medical Certificate'), ('ID_PROOF', 'Parent ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('OTHER', 'Other')], max_length=30)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admissionenquiry')),
            ],
            options={
                'verbose_name': 'Admission Document',
                'verbose_name_plural': 'Admission Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_type', models.CharField(choices=[('NOTE', 'Note'), ('CALL', 'Phone Call'), ('VISIT', 'Campus Visit'), ('EMAIL', 'Email Sent'), ('STATUS_CHANGE', 'Status Change'), ('SYSTEM', 'System')], default='NOTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notes', to='admissions.admissionenquiry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Note',
                'verbose_name_plural': 'Admission Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('form_fields', models.JSONField(default=dict, help_text='Customizable form fields configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sessions', to='academic_sessions.academicyear')),
                ('grades_open', models.ManyToManyField(blank=True, related_name='admission_sessions', to='students.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sessions', to='schools.school')),
            ],
            options={
                'verbose_name': 'Admission Session',
                'verbose_name_plural': 'Admission Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='admissions.admissionsession'),
        ),
        migrations.AddIndex(
            model_name='admissionsession',
            index=models.Index(fields=['school', 'is_active'], name='admissions__school__96e5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['school', 'stage'], name='admissions__school__568020_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['school', 'next_followup_date'], name='admissions__school__2c4223_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionenquiry',
            index=models.Index(fields=['parent_phone'], name='admissions__parent__c26545_idx'),
        ),
    ]
