# Generated by Django 5.2.11 on 2026-02-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_replace_grade_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='is_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether admission fee has been collected'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='allow_stage_bypass',
            field=models.BooleanField(default=False, help_text='Allow staff to move enquiries between non-sequential stages (skip ahead)'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='enabled_stages',
            field=models.JSONField(default=list, help_text="Ordered list of enabled stage keys for this session, e.g. ['NEW', 'APPROVED', 'ENROLLED']"),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='require_campus_visit',
            field=models.BooleanField(default=False, help_text='Whether campus visit is required for this admission session'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='require_entrance_test',
            field=models.BooleanField(default=False, help_text='Whether entrance test is required for this admission session'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='require_fee_before_enrollment',
            field=models.BooleanField(default=True, help_text='If True, payment must be confirmed before enquiry reaches ENROLLED stage'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='require_parent_interview',
            field=models.BooleanField(default=False, help_text='Whether parent interview is required for this admission session'),
        ),
        migrations.AddField(
            model_name='admissionsession',
            name='workflow_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple: Quick Approval (3 stages)'), ('STANDARD', 'Standard: Moderate Process (5 stages)'), ('COMPLEX', 'Complex: Full Pipeline (10+ stages)'), ('CUSTOM', 'Custom: School-Defined')], default='STANDARD', help_text='Predefined workflow template for this admission session', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='stage',
            field=models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('VISIT_SCHEDULED', 'Campus Visit Scheduled'), ('VISIT_DONE', 'Campus Visit Done'), ('FORM_SUBMITTED', 'Application Submitted'), ('TEST_SCHEDULED', 'Test Scheduled'), ('TEST_DONE', 'Test Completed'), ('OFFERED', 'Offer Made'), ('ACCEPTED', 'Accepted'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('LOST', 'Lost')], default='NEW', help_text='Current stage in the admission pipeline (may be overridden by configured stages)', max_length=50),
        ),
        migrations.CreateModel(
            name='AdmissionStageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(help_text="Unique key for this stage (e.g., 'NEW', 'APPROVED', 'PAYMENT_PENDING')", max_length=50)),
                ('stage_label', models.CharField(help_text="Display label for this stage (e.g., 'New Enquiry', 'Approved')", max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Position in the workflow (lower numbers are earlier stages)')),
                ('is_optional', models.BooleanField(default=False, help_text='If True, this stage can be skipped (only if session.allow_stage_bypass=True)')),
                ('is_blocking', models.BooleanField(default=False, help_text='If True, cannot proceed past this stage until stage requirements are met')),
                ('description', models.TextField(blank=True, default='', help_text='Description of what happens in this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='Admission session this stage configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stage_configs', to='admissions.admissionsession')),
            ],
            options={
                'verbose_name': 'Admission Stage Configuration',
                'verbose_name_plural': 'Admission Stage Configurations',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='current_stage_config',
            field=models.ForeignKey(blank=True, help_text='Reference to the enabled stage configuration for this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='admissions.admissionstageconfig'),
        ),
        migrations.CreateModel(
            name='AdmissionFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total fee amount to be collected', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid by parent', max_digits=10)),
                ('fee_type', models.CharField(choices=[('REGISTRATION', 'Registration Fee'), ('ADMISSION', 'Admission Fee'), ('FULL_PAYMENT', 'Full Year Payment'), ('DEPOSIT', 'Deposit Amount')], default='ADMISSION', help_text='Type/category of fee', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial Payment'), ('COMPLETED', 'Payment Received'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current payment status', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when fee was fully paid', null=True)),
                ('transaction_id', models.CharField(blank=True, default='', help_text='External payment gateway transaction ID', max_length=100)),
                ('payment_method', models.CharField(blank=True, default='', help_text="Payment method used (e.g., 'UPI', 'BANK_TRANSFER', 'CASH')", max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about the fee/payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.OneToOneField(help_text='Parent admission enquiry for this fee record', on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='admissions.admissionenquiry')),
            ],
            options={
                'verbose_name': 'Admission Fee Record',
                'verbose_name_plural': 'Admission Fee Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enquiry', 'status'], name='admissions__enquiry_8a3a72_idx'), models.Index(fields=['status'], name='admissions__status_172b9a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='admissionstageconfig',
            index=models.Index(fields=['session', 'order'], name='admissions__session_133c8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionstageconfig',
            unique_together={('session', 'stage_key')},
        ),
    ]
