# Generated by Django 5.2.11 on 2026-02-16 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_add_workflow_config_and_fee_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('to_stage', models.CharField(max_length=50)),
                ('bypassed', models.BooleanField(default=False, help_text='Whether this stage was bypassed')),
                ('bypass_reason', models.TextField(blank=True, default='', help_text='Reason for bypassing this stage')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bypass_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_bypasses', to=settings.AUTH_USER_MODEL)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_change_logs', to='admissions.admissionenquiry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stage Change Log',
                'verbose_name_plural': 'Stage Change Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['enquiry', 'created_at'], name='admissions__enquiry_6aafc8_idx')],
            },
        ),
    ]
