# Generated by Django 5.2.11 on 2026-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_simplify_admissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admissionenquiry',
            new_name='admissions__school__2a61e8_idx',
            old_name='admissions__school__status_idx',
        ),
        migrations.RenameIndex(
            model_name='admissionenquiry',
            new_name='admissions__mobile_5cba3d_idx',
            old_name='admissions__mobile__idx',
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='applying_for_grade_level',
            field=models.IntegerField(blank=True, help_text='Grade level applying for (e.g., 0=Playgroup, 3=Class 1)', null=True),
        ),
    ]
