# Generated by Django 5.2.11 on 2026-04-07 08:12

from django.db import migrations

SECTIONS = [
    {
        'key': 'introduction',
        'title': 'Introducing KoderEduAI',
        'order': 0,
        'content_html': """<p><strong>KoderEduAI</strong> is a cloud-based, AI-powered School ERP platform designed for modern educational institutions — from single-branch schools to large multi-campus networks.</p>
<p>Built on a multi-tenant architecture, every school on the platform gets a fully isolated environment with role-based access, real-time data, and intelligent automation built in from day one.</p>
<blockquote>We don't just digitise your school — we make it smarter.</blockquote>
<p>From AI-assisted attendance reading to automated fee collection, timetable management to parent portals, KoderEduAI is the single platform that replaces dozens of disconnected tools.</p>""",
    },
    {
        'key': 'use-cases',
        'title': 'Who Is It For?',
        'order': 1,
        'content_html': """<p>KoderEduAI serves a wide range of educational institutions:</p>
<ul>
  <li><strong>Private K-12 Schools</strong> — Full academic year lifecycle: enrolments, timetables, exams, report cards, and parent communication.</li>
  <li><strong>Multi-Branch School Networks</strong> — One admin dashboard to manage all branches. Each campus gets its own isolated data and staff.</li>
  <li><strong>Coaching Institutes &amp; Tuition Centres</strong> — Fast student registration, flexible fee plans, and attendance in seconds.</li>
  <li><strong>International Schools</strong> — Multi-currency finance, modular curriculum builder, and cloud-first infrastructure.</li>
  <li><strong>Government-Aided Schools</strong> — Budget-friendly tiers, offline-capable mobile attendance, and bulk reporting tools.</li>
</ul>
<p>No matter the size — 50 students or 5,000 — KoderEduAI scales without configuration overhead.</p>""",
    },
    {
        'key': 'benefits',
        'title': 'Key Benefits',
        'order': 2,
        'content_html': """<h3>Save Time. Reduce Errors. Delight Parents.</h3>
<ul>
  <li><strong>AI Attendance from Paper Registers</strong> — Photograph a handwritten register and let the AI populate records automatically. Zero manual entry.</li>
  <li><strong>Instant Report Cards</strong> — Generate beautifully formatted PDF report cards for all students with one click.</li>
  <li><strong>Real-Time Fee Tracking</strong> — Automated payment reminders, overdue alerts, and financial dashboards that update the moment a payment lands.</li>
  <li><strong>Unified Parent Portal</strong> — Parents access attendance, marks, fee balances, and communicate with teachers — all from one mobile-friendly app.</li>
  <li><strong>Zero IT Overhead</strong> — Hosted, maintained, and updated by us. Your staff just logs in.</li>
  <li><strong>Role-Based Security</strong> — Nine user roles with granular permissions. Teachers see only their classes; accountants see only finance.</li>
</ul>""",
    },
    {
        'key': 'automations',
        'title': 'Powerful Automations',
        'order': 3,
        'content_html': """<p>KoderEduAI replaces repetitive administrative work with intelligent, configurable automations:</p>
<h3>Attendance Automations</h3>
<ul>
  <li>AI reads scanned handwritten registers and auto-fills records.</li>
  <li>Absent students trigger SMS/WhatsApp notifications to parents automatically.</li>
  <li>Monthly attendance summaries emailed to principals with no manual effort.</li>
</ul>
<h3>Finance Automations</h3>
<ul>
  <li>Fee schedules auto-generate invoices at the start of each term.</li>
  <li>Overdue reminders escalate via SMS → WhatsApp → email on configurable schedules.</li>
  <li>Salary slips generated and distributed to staff each month automatically.</li>
</ul>
<h3>Academic Automations</h3>
<ul>
  <li>Year-end student promotions run in bulk with one approval click.</li>
  <li>Exam timetables auto-populate the student and teacher portals.</li>
  <li>Assignment due-date reminders sent to students via the LMS module.</li>
</ul>
<h3>Communication Automations</h3>
<ul>
  <li>Holiday announcements and circular letters delivered to all parents instantly.</li>
  <li>Leave request approvals notify teachers and parents in real time.</li>
</ul>""",
    },
    {
        'key': 'pricing',
        'title': 'Subscription Pricing',
        'order': 4,
        'content_html': """<p>KoderEduAI is priced as a base platform + optional module add-ons. Choose what you need — pay only for what you use.</p>
<h3>Base Platform Tiers</h3>
<table>
  <thead>
    <tr><th>Plan</th><th>Monthly</th><th>Includes</th></tr>
  </thead>
  <tbody>
    <tr><td><strong>Starter</strong></td><td>₦5,000</td><td>Up to 200 students · Core modules (Attendance, Students, Timetable) · 1 branch</td></tr>
    <tr><td><strong>Growth</strong></td><td>₦8,000</td><td>Up to 800 students · All core + Finance + Exams + Parent Portal · 2 branches</td></tr>
    <tr><td><strong>Enterprise</strong></td><td>₦12,000</td><td>Unlimited students · All modules included · Unlimited branches · Priority support</td></tr>
  </tbody>
</table>
<h3>Module Add-Ons (per school/month)</h3>
<table>
  <thead>
    <tr><th>Module</th><th>Add-On Price</th></tr>
  </thead>
  <tbody>
    <tr><td>HR &amp; Payroll</td><td>₦3,000</td></tr>
    <tr><td>Transport Management</td><td>₦3,500</td></tr>
    <tr><td>Library Management</td><td>₦3,000</td></tr>
    <tr><td>Hostel Management</td><td>₦4,000</td></tr>
    <tr><td>Inventory Control</td><td>₦3,500</td></tr>
    <tr><td>LMS &amp; Curriculum Builder</td><td>₦4,500</td></tr>
    <tr><td>Admissions CRM</td><td>₦5,000</td></tr>
  </tbody>
</table>
<p><em>All prices are in Nigerian Naira (NGN). Annual billing available at 2 months free.</em></p>""",
    },
    {
        'key': 'faq',
        'title': 'Frequently Asked Questions',
        'order': 5,
        'content_html': """<h3>Do we need special hardware?</h3>
<p>We support both models — cloud-only (zero hardware) and on-device setups with cameras or biometrics. Your existing phones or tablets are sufficient for attendance capture.</p>

<h3>How long does setup take?</h3>
<p>Most schools are fully operational within 48 hours. Our onboarding team handles data import, user setup, and staff training at no extra charge.</p>

<h3>Is our data safe?</h3>
<p>Yes. All data is encrypted at rest and in transit. Each school's data is fully isolated — no cross-tenant access is possible by design.</p>

<h3>Can we switch plans later?</h3>
<p>Absolutely. You can upgrade, downgrade, or add modules at any time. Changes take effect on the next billing cycle.</p>

<h3>Do you offer offline access?</h3>
<p>The mobile app supports offline attendance capture. Data syncs automatically when connectivity is restored.</p>

<h3>What support is included?</h3>
<p>All plans include email support. Growth and Enterprise plans include WhatsApp/phone support during business hours. Enterprise adds a dedicated account manager.</p>""",
    },
]


def seed_sections(apps, schema_editor):
    BrochureSection = apps.get_model('brochure', 'BrochureSection')
    for s in SECTIONS:
        BrochureSection.objects.get_or_create(
            key=s['key'],
            defaults={
                'title': s['title'],
                'order': s['order'],
                'content': {},
                'content_html': s['content_html'],
                'is_visible': True,
            },
        )


def unseed_sections(apps, schema_editor):
    BrochureSection = apps.get_model('brochure', 'BrochureSection')
    BrochureSection.objects.filter(key__in=[s['key'] for s in SECTIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_sections, reverse_code=unseed_sections),
    ]
