# Generated by Django 5.2.11 on 2026-04-28 13:22

import brochure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0002_seed_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('role_applied', models.CharField(max_length=120)),
                ('cover_letter', models.TextField()),
                ('cv_file', models.FileField(upload_to=brochure.models.career_cv_upload_path)),
                ('source', models.CharField(default='landing-page', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
