# Generated by Django 5.2.11 on 2026-04-28 16:50

import brochure.models
import brochure.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0003_careerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='cv_file',
            field=models.FileField(storage=brochure.storage.CareerCVSupabaseStorage(), upload_to=brochure.models.career_cv_upload_path),
        ),
    ]
