# Generated by Django 5.2.11 on 2026-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0004_alter_careerapplication_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('source', models.CharField(default='landing-page', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('source', models.CharField(default='landing-page', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
