# Generated by Django 5.2.11 on 2026-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochure', '0005_add_demo_request_contact_enquiry_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='visitor_credentials_email_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='visitor_credentials_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
