# Generated by Django 5.2.11 on 2026-02-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date', '-id'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
    ]
