# Generated by Django 5.2.11 on 2026-02-19 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_exam_group_model'),
        ('lms', '0002_alter_assignment_options'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0010_fix_class_name_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether the content was AI-generated'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='content_mode',
            field=models.CharField(choices=[('TOPICS', 'Topics'), ('FREEFORM', 'Free-form')], default='FREEFORM', help_text='Whether this plan uses structured topics or free-form text', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='display_text',
            field=models.TextField(blank=True, help_text='Pre-formatted topic display text, computed on save'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('sd', 'Sindhi'), ('ps', 'Pashto'), ('pa', 'Punjabi'), ('other', 'Other')], default='en', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_books', to='students.class', verbose_name='Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_books', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_books', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Curriculum Book',
                'verbose_name_plural': 'Curriculum Books',
                'ordering': ['class_obj', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('chapter_number', models.PositiveIntegerField(help_text='Chapter ordering number (1, 2, 3...)')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lms.book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('topic_number', models.PositiveIntegerField(help_text='Topic ordering within chapter (1, 2, 3...)')),
                ('description', models.TextField(blank=True)),
                ('estimated_periods', models.PositiveIntegerField(default=1, help_text='Estimated teaching periods needed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lms.chapter')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['topic_number'],
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='planned_topics',
            field=models.ManyToManyField(blank=True, help_text='Topics planned for this lesson (from curriculum books)', related_name='lesson_plans', to='lms.topic'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['school', 'class_obj', 'subject'], name='lms_book_school__e54a60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('chapter', 'topic_number')},
        ),
    ]
