# Generated by Django 5.2.11 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_add_curriculum_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Structured rich content blocks for chapter-level notes'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_blocks_schema_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Schema version of content_blocks payload'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_text',
            field=models.TextField(blank=True, help_text='Flattened plain text derived from content blocks for search/prompting'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content_version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic content revision number for chapter content'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='needs_migration',
            field=models.BooleanField(default=False, help_text='True when stored content blocks require schema migration'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, help_text='Optional last page for this chapter in the source book', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, help_text='Optional first page for this chapter in the source book', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, help_text='Structured rich content blocks for topic details'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_blocks_schema_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Schema version of content_blocks payload'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_kind',
            field=models.CharField(default='general', help_text='Primary classification for topic content (for example general or exercise)', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_text',
            field=models.TextField(blank=True, help_text='Flattened plain text derived from content blocks for search/prompting'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic content revision number for topic content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='needs_migration',
            field=models.BooleanField(default=False, help_text='True when stored content blocks require schema migration'),
        ),
        migrations.AddField(
            model_name='topic',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, help_text='Optional last page for this topic in the source book', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, help_text='Optional first page for this topic in the source book', null=True),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'chapter_number'], name='lms_chapter_book_id_d42d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'page_start'], name='lms_chapter_book_id_b80f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['chapter', 'topic_number'], name='lms_topic_chapter_31f950_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['chapter', 'page_start'], name='lms_topic_chapter_abf9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['content_kind'], name='lms_topic_content_04840a_idx'),
        ),
    ]
