# Generated by Django 6.0.4 on 2026-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_curriculum_rich_content_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chapter',
            new_name='lms_chapter_book_id_6ef067_idx',
            old_name='lms_chapter_book_id_d42d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='chapter',
            new_name='lms_chapter_book_id_b6546d_idx',
            old_name='lms_chapter_book_id_b80f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='lms_topic_chapter_56f4ff_idx',
            old_name='lms_topic_chapter_31f950_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='lms_topic_chapter_429940_idx',
            old_name='lms_topic_chapter_abf9cc_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='lms_topic_content_acda7c_idx',
            old_name='lms_topic_content_04840a_idx',
        ),
        migrations.AddField(
            model_name='assignment',
            name='requires_submission',
            field=models.BooleanField(default=True, help_text='Whether students can submit work for this assignment. Always False for DIARY.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('DIARY', 'Diary'), ('PROJECT', 'Project'), ('CLASSWORK', 'Classwork'), ('LAB', 'Lab')], default='HOMEWORK', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Required for submission-based types. Optional for DIARY.', null=True),
        ),
    ]
