# Generated by Django 5.2.11 on 2026-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_tocimportjob'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subtopic',
            name='lms_subtopic_topic_sn_idx',
        ),
    ]
