# Generated by Django 6.0.4 on 2026-05-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_subtopic_lms_subtopic_topic_sn_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Paragraph'), ('definition', 'Definition'), ('example', 'Worked Example'), ('exercise', 'Exercise'), ('formula', 'Formula / Equation'), ('diagram_desc', 'Diagram Description'), ('summary', 'Summary'), ('key_point', 'Key Point')], default='text', max_length=30)),
                ('content_text', models.TextField()),
                ('content_rich', models.JSONField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('difficulty_level', models.IntegerField(blank=True, null=True)),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_rel', to='lms.chapter')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_rel', to='lms.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks_rel', to='lms.topic')),
            ],
            options={
                'ordering': ['sequence_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('chapter__isnull', False), ('topic__isnull', False), ('subtopic__isnull', False), _connector='OR'), name='content_block_has_parent')],
            },
        ),
    ]
