# Generated by Django 6.0.4 on 2026-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='content_blocks_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='content_schema_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='estimated_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
