# Generated by Django 6.0.4 on 2026-05-25 05:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_subtopic_content_blocks_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
