# Generated by Django 6.0.4 on 2026-05-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('examinations', '0019_question_embedding'),
        ('lms', '0011_contentblock_embedding_topic_embedding'),
        ('schools', '0016_alter_school_module_entitlements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('concept', 'Concept'), ('skill', 'Skill'), ('keyword', 'Keyword'), ('standard', 'Curriculum Standard')], max_length=20)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_tags', to='schools.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_tags', to='academics.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='examinations.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='lms.tag')),
            ],
            options={
                'unique_together': {('question', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlockTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_block_tags', to='lms.contentblock')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_block_tags', to='lms.tag')),
            ],
            options={
                'unique_together': {('content_block', 'tag')},
            },
        ),
    ]
