# Generated by Django 6.0.4 on 2026-05-25 06:13

import django.db.models.deletion
from django.db import migrations, models


def seed_learning_objectives(apps, schema_editor):
    LessonPlan = apps.get_model('lms', 'LessonPlan')
    LearningObjective = apps.get_model('lms', 'LearningObjective')
    LessonPlanObjective = apps.get_model('lms', 'LessonPlanObjective')

    for lesson_plan in LessonPlan.objects.exclude(objectives='').iterator():
        raw_text = (lesson_plan.objectives or '').strip()
        if not raw_text:
            continue

        statements = []
        for line in raw_text.splitlines():
            statement = line.strip().lstrip('-').lstrip('*').strip()
            if statement:
                statements.append(statement)
        if not statements:
            statements = [raw_text]

        topics = list(lesson_plan.planned_topics.all())
        if not topics:
            continue

        for topic in topics:
            for statement in statements:
                objective, _ = LearningObjective.objects.get_or_create(
                    topic_id=topic.id,
                    statement=statement,
                    defaults={
                        'bloom_level': 'understand',
                        'is_ai_generated': lesson_plan.ai_generated,
                        'is_active': True,
                    },
                )
                LessonPlanObjective.objects.get_or_create(
                    lesson_plan_id=lesson_plan.id,
                    objective_id=objective.id,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_tag_questiontag_contentblocktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='lms.topic')),
            ],
            options={
                'ordering': ['topic_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_objectives', to='lms.lessonplan')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_links', to='lms.learningobjective')),
            ],
            options={
                'unique_together': {('lesson_plan', 'objective')},
            },
        ),
        migrations.RunPython(seed_learning_objectives, noop_reverse),
    ]
