# Generated by Django 6.0.4 on 2026-05-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('lms', '0013_learningobjective_lessonplanobjective'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=50)),
                ('board', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'board'],
            },
        ),
        migrations.CreateModel(
            name='StandardObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('statement', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_objectives', to='students.class')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='lms.curriculumstandard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_objectives', to='academics.subject')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('standard', 'subject', 'grade', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TopicStandardAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_alignments', to='lms.standardobjective')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_alignments', to='lms.topic')),
            ],
            options={
                'unique_together': {('topic', 'objective')},
            },
        ),
    ]
