# Generated by Django 6.0.4 on 2026-05-25 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_curriculumstandard_standardobjective_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('content_rich', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('revision_note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_revisions', to=settings.AUTH_USER_MODEL)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lms.contentblock')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
