# Generated by Django 6.0.4 on 2026-07-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_contentrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='custom_topics',
            field=models.JSONField(blank=True, default=list, help_text='Freeform topic labels typed by the teacher (not linked to a book), shown alongside planned_topics/planned_subtopics in display_text'),
        ),
    ]
