# Generated by Django 6.0.4 on 2026-07-31 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0015_studentrisksnapshot'),
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('hr', '0003_fix_stuck_inactive_staff'),
        ('lms', '0016_lessonplan_custom_topics'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='session_class',
            field=models.ForeignKey(blank=True, help_text='Section/session class this plan applies to. Null means it applies to every section of the master class (legacy behavior, kept for old rows).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academic_sessions.sessionclass'),
        ),
        migrations.AddIndex(
            model_name='lessonplan',
            index=models.Index(fields=['session_class'], name='lms_lessonp_session_c30e49_idx'),
        ),
    ]
