# Generated by Django 5.2.11 on 2026-09-13 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0015_studentrisksnapshot'),
        ('lms', '0018_backfill_class2_section_a_lesson_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, help_text='When this topic is planned to be taught this academic year', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_schedules', to='academic_sessions.academicyear')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lms.topic')),
            ],
            options={
                'verbose_name': 'Topic Schedule',
                'verbose_name_plural': 'Topic Schedules',
                'indexes': [models.Index(fields=['topic', 'academic_year'], name='lms_topicsc_topic_i_ddde6d_idx')],
                'unique_together': {('topic', 'academic_year')},
            },
        ),
    ]
