# Generated by Django 5.2.11 on 2026-09-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_studentenrollment_left_date'),
        ('lms', '0019_topic_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='session_class',
            field=models.ForeignKey(blank=True, help_text='Set for a section-only assignment. Null = every section of class_obj.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academic_sessions.sessionclass'),
        ),
    ]
