# Generated by Django 6.0.1 on 2026-02-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('academics', '0002_academicsaichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='academic_sessions.academicyear'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year for this timetable entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='academic_sessions.academicyear'),
        ),
    ]
