# Generated by Django 5.2.11 on 2026-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_session_scoped_roll_numbers'),
        ('academics', '0003_add_academic_year_to_academics'),
        ('hr', '0001_initial'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0009_session_scoped_roll_numbers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['teacher'], name='academics_c_teacher_68a872_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['academic_year'], name='academics_c_academi_ea455c_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='academics_s_school__ea36ae_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day', 'slot'], name='academics_t_teacher_a7b7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'class_obj', 'day'], name='academics_t_school__3b7fb6_idx'),
        ),
    ]
