# Generated by Django 5.2.11 on 2026-02-26 18:08

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_exam_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='applicable_days',
            field=models.JSONField(default=academics.models.default_applicable_days, help_text='Days this slot applies to, e.g. ["MON","TUE","WED","THU","FRI","SAT"]'),
        ),
    ]
