# Generated by Django 5.2.11 on 2026-04-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0012_rename_academic_se_school__f1331a_idx_academic_se_school__3d73df_idx_and_more'),
        ('academics', '0006_classteacherassignment'),
        ('hr', '0001_initial'),
        ('schools', '0014_school_exam_config'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classteacherassignment',
            options={'ordering': ['class_obj__grade_level', 'class_obj__name', 'session_class__section', 'teacher__first_name']},
        ),
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='academics_c_school__ea897e_idx',
            old_name='academics_cl_school__fa2af5_idx',
        ),
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='academics_c_teacher_9c2f67_idx',
            old_name='academics_cl_teacher_feaaf8_idx',
        ),
        migrations.RenameIndex(
            model_name='classteacherassignment',
            new_name='academics_c_class_o_23f318_idx',
            old_name='academics_cl_class_o_63d658_idx',
        ),
        migrations.AlterUniqueTogether(
            name='classteacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='session_class',
            field=models.ForeignKey(blank=True, help_text='Specific session class (with section). Enables section-level teacher assignment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academic_sessions.sessionclass'),
        ),
        migrations.AlterField(
            model_name='classteacherassignment',
            name='class_obj',
            field=models.ForeignKey(help_text='Master class (for backward compat + quick access). Section level tracked via session_class.', on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='students.class', verbose_name='Class'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacherassignment',
            unique_together={('school', 'academic_year', 'session_class', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='classteacherassignment',
            index=models.Index(fields=['session_class', 'academic_year', 'is_active'], name='academics_c_session_0d97a7_idx'),
        ),
    ]
