# Generated by Django 6.0.4 on 2026-04-23 08:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_classsubject_session_class(apps, schema_editor):
    ClassSubject = apps.get_model('academics', 'ClassSubject')
    SessionClass = apps.get_model('academic_sessions', 'SessionClass')

    existing_pairs = set(
        ClassSubject.objects.exclude(session_class_id=None).values_list(
            'school_id', 'academic_year_id', 'session_class_id', 'subject_id'
        )
    )

    source_rows = list(
        ClassSubject.objects.filter(session_class_id=None).order_by('id')
    )

    for class_subject in source_rows:
        if not class_subject.academic_year_id or not class_subject.class_obj_id:
            continue

        matches = list(
            SessionClass.objects.filter(
                school_id=class_subject.school_id,
                academic_year_id=class_subject.academic_year_id,
                class_obj_id=class_subject.class_obj_id,
            ).order_by('grade_level', 'display_name', 'section', 'id')
        )

        if not matches:
            continue

        primary = matches[0]
        class_subject.session_class_id = primary.id
        class_subject.save(update_fields=['session_class'])
        existing_pairs.add((
            class_subject.school_id,
            class_subject.academic_year_id,
            primary.id,
            class_subject.subject_id,
        ))

        for match in matches[1:]:
            key = (
                class_subject.school_id,
                class_subject.academic_year_id,
                match.id,
                class_subject.subject_id,
            )
            if key in existing_pairs:
                continue

            clone = ClassSubject.objects.create(
                school_id=class_subject.school_id,
                academic_year_id=class_subject.academic_year_id,
                session_class_id=match.id,
                class_obj_id=class_subject.class_obj_id,
                subject_id=class_subject.subject_id,
                teacher_id=class_subject.teacher_id,
                periods_per_week=class_subject.periods_per_week,
                is_active=class_subject.is_active,
            )
            existing_pairs.add((
                clone.school_id,
                clone.academic_year_id,
                clone.session_class_id,
                clone.subject_id,
            ))


def reverse_backfill_classsubject_session_class(apps, schema_editor):
    ClassSubject = apps.get_model('academics', 'ClassSubject')
    ClassSubject.objects.update(session_class_id=None)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('academic_sessions', '0012_rename_academic_se_school__f1331a_idx_academic_se_school__3d73df_idx_and_more'),
        ('academics', '0008_backfill_session_class'),
        ('hr', '0001_initial'),
        ('schools', '0014_school_exam_config'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['class_obj__grade_level', 'class_obj__name', 'session_class__section', 'subject__name']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE academics_classsubject
                    ADD COLUMN IF NOT EXISTS session_class_id bigint NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'academics_classsubject_session_class_id_fk'
                        ) THEN
                            ALTER TABLE academics_classsubject
                            ADD CONSTRAINT academics_classsubject_session_class_id_fk
                            FOREIGN KEY (session_class_id)
                            REFERENCES academic_sessions_sessionclass(id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END
                    $$;

                    CREATE INDEX IF NOT EXISTS academics_classsubject_session_class_id_idx
                    ON academics_classsubject (session_class_id);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS academics_classsubject_session_class_id_idx;
                    ALTER TABLE academics_classsubject DROP CONSTRAINT IF EXISTS academics_classsubject_session_class_id_fk;
                    ALTER TABLE academics_classsubject DROP COLUMN IF EXISTS session_class_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='classsubject',
                    name='session_class',
                    field=models.ForeignKey(blank=True, help_text='Specific session class (with section). Enables section-level subject assignment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academic_sessions.sessionclass'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    DECLARE
                        school_attnum smallint;
                        class_attnum smallint;
                        subject_attnum smallint;
                        constraint_name text;
                    BEGIN
                        SELECT attnum INTO school_attnum
                        FROM pg_attribute
                        WHERE attrelid = 'academics_classsubject'::regclass
                          AND attname = 'school_id'
                          AND NOT attisdropped;

                        SELECT attnum INTO class_attnum
                        FROM pg_attribute
                        WHERE attrelid = 'academics_classsubject'::regclass
                          AND attname = 'class_obj_id'
                          AND NOT attisdropped;

                        SELECT attnum INTO subject_attnum
                        FROM pg_attribute
                        WHERE attrelid = 'academics_classsubject'::regclass
                          AND attname = 'subject_id'
                          AND NOT attisdropped;

                        FOR constraint_name IN
                            SELECT conname
                            FROM pg_constraint
                            WHERE conrelid = 'academics_classsubject'::regclass
                              AND contype = 'u'
                              AND conkey = ARRAY[school_attnum, class_attnum, subject_attnum]
                        LOOP
                            EXECUTE format('ALTER TABLE academics_classsubject DROP CONSTRAINT %I', constraint_name);
                        END LOOP;
                    END
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='classsubject',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.RunPython(
            backfill_classsubject_session_class,
            reverse_backfill_classsubject_session_class,
            atomic=False,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE UNIQUE INDEX IF NOT EXISTS academics_cls_subj_school_year_session_subject_uniq
                    ON academics_classsubject (school_id, academic_year_id, session_class_id, subject_id);
                    """,
                    reverse_sql="""
                    DROP INDEX IF EXISTS academics_cls_subj_school_year_session_subject_uniq;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='classsubject',
                    unique_together={('school', 'academic_year', 'session_class', 'subject')},
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['session_class', 'academic_year', 'is_active'], name='academics_c_session_4d8db2_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_obj', 'academic_year', 'is_active'], name='academics_c_class_o_ebfea5_idx'),
        ),
    ]
