# Generated by Django 5.2.11 on 2026-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_academicsanalyticsalert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='academicsanalyticsalert',
            new_name='academics_a_school__118017_idx',
            old_name='academics_a_school__d365d7_idx',
        ),
        migrations.RenameIndex(
            model_name='academicsanalyticsalert',
            new_name='academics_a_school__f4c484_idx',
            old_name='academics_a_school__f90aaf_idx',
        ),
    ]
