# Generated by Django 5.2.11 on 2026-09-25 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_studentenrollment_left_date'),
        ('academics', '0011_rename_academics_a_school__d365d7_idx_academics_a_school__118017_idx_and_more'),
        ('hr', '0004_staffdocument_expiry_date'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='session_class',
            field=models.ForeignKey(blank=True, help_text='Set for a section-only entry that overrides the shared (class-wide) entry at the same day/slot. Null = shared by every section of class_obj.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academic_sessions.sessionclass'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'session_class', 'day'], name='academics_t_school__a81181_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('session_class__isnull', True)), fields=('school', 'class_obj', 'day', 'slot'), name='unique_shared_timetable_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('session_class__isnull', False)), fields=('school', 'session_class', 'day', 'slot'), name='unique_section_timetable_slot'),
        ),
    ]
