# Generated by Django 6.0.1 on 2026-02-10 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_alter_school_subdomain'),
        ('students', '0002_make_parent_phone_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SUPPLIES', 'Supplies'), ('MAINTENANCE', 'Maintenance'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(help_text='Date the expense was incurred')),
                ('description', models.TextField(blank=True, help_text='Description of the expense')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schools.school')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'date'], name='finance_exp_school__6d3bf3_idx'), models.Index(fields=['school', 'category'], name='finance_exp_school__308237_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g. 2026)')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Total amount due for this month', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid', max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=10)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was received', null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Manual receipt number for reference', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collections', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-year', '-month', 'student__class_obj', 'student__roll_number'],
                'indexes': [models.Index(fields=['school', 'year', 'month'], name='finance_fee_school__58b9a5_idx'), models.Index(fields=['school', 'status'], name='finance_fee_school__e1c624_idx')],
                'unique_together': {('school', 'student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Monthly fee amount', max_digits=10)),
                ('effective_from', models.DateField(help_text='Date from which this fee structure is effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this fee is effective (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(blank=True, help_text='Set fee for an entire class (leave student blank)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.class', verbose_name='Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.school')),
                ('student', models.ForeignKey(blank=True, help_text='Override fee for a specific student (takes precedence over class fee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['school', 'class_obj'], name='finance_fee_school__9cfb16_idx'), models.Index(fields=['school', 'student'], name='finance_fee_school__339bc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinanceAIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Optional metadata: query data used, tokens, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_chat_messages', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance AI Chat Message',
                'verbose_name_plural': 'Finance AI Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['school', 'user', 'created_at'], name='finance_fin_school__a4acd4_idx')],
            },
        ),
    ]
