# Generated by Django 6.0.1 on 2026-02-10 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('schools', '0003_alter_school_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carried-forward balance from previous month', max_digits=10),
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALE', 'Sale (Books/Copies/Uniform)'), ('DONATION', 'Donation'), ('EVENT', 'Event Income'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(help_text='Date the income was received')),
                ('description', models.TextField(blank=True, help_text='Description of the income')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_other_incomes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_incomes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Other Income',
                'verbose_name_plural': 'Other Incomes',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'date'], name='finance_oth_school__8e29d2_idx'), models.Index(fields=['school', 'category'], name='finance_oth_school__a9e303_idx')],
            },
        ),
    ]
