# Generated by Django 6.0.1 on 2026-02-10 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feepayment_previous_balance_otherincome'),
        ('schools', '0003_alter_school_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Principal Branch 1, Fund Branch 1, Shah Mir', max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('PERSON', 'Person')], default='CASH', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Beginning Balance Forward (BBF)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='schools.school')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account from which this expense was paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.account'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account that received this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account that received this income', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_incomes', to='finance.account'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(help_text='Date of the transfer')),
                ('description', models.TextField(blank=True, help_text='Reason or notes for the transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='finance.account')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transfers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='schools.school')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='finance.account')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['school', 'is_active'], name='finance_acc_school__419ec5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['school', 'date'], name='finance_tra_school__29e588_idx'),
        ),
    ]
