# Generated by Django 6.0.1 on 2026-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_expense_account_feepayment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='staff_visible',
            field=models.BooleanField(default=True, help_text='Whether staff members can see this account and its transactions'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Hide this expense from staff members'),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Hide this income from staff members'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Hide this transfer from staff members'),
        ),
    ]
