# Generated by Django 6.0.1 on 2026-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_staff_visible_expense_is_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid'), ('ADVANCE', 'Advance')], default='UNPAID', max_length=10),
        ),
    ]
