# Generated by Django 6.0.1 on 2026-02-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_advance_status'),
        ('schools', '0004_organization_school_organization_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this account belongs to (for shared accounts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='schools.organization'),
        ),
        migrations.AlterField(
            model_name='account',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this account belongs to (null = shared across org)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False)), fields=('school', 'name'), name='unique_account_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', True)), fields=('organization', 'name'), name='unique_account_name_per_org'),
        ),
    ]
