# Generated by Django 6.0.1 on 2026-02-12 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_account_unique_together_account_organization_and_more'),
        ('schools', '0006_alter_userschoolmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year, e.g. 2026')),
                ('month', models.IntegerField(help_text='Calendar month (1-12)')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_months', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closings', to='schools.school')),
            ],
            options={
                'verbose_name': 'Monthly Closing',
                'verbose_name_plural': 'Monthly Closings',
                'ordering': ['-year', '-month'],
                'unique_together': {('school', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Net balance as of last day of the closed month', max_digits=12)),
                ('opening_balance_used', models.DecimalField(decimal_places=2, default=0, help_text='BBF used to compute this snapshot', max_digits=12)),
                ('receipts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfers_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfers_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.account')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='finance.monthlyclosing')),
            ],
            options={
                'verbose_name': 'Account Snapshot',
                'verbose_name_plural': 'Account Snapshots',
                'ordering': ['account__name'],
                'unique_together': {('closing', 'account')},
            },
        ),
    ]
