# Generated by Django 6.0.1 on 2026-02-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('finance', '0007_monthlyclosing_accountsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this payment belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='academic_sessions.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this fee structure applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='academic_sessions.academicyear'),
        ),
    ]
