# Generated by Django 6.0.1 on 2026-02-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('finance', '0008_add_academic_year_to_finance'),
        ('schools', '0010_alter_userschoolmembership_role'),
        ('students', '0004_student_address_student_admission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_to', models.CharField(choices=[('ALL', 'All Students'), ('GRADE', 'Specific Grade'), ('CLASS', 'Specific Class'), ('STUDENT', 'Individual Student'), ('SIBLING', 'Siblings (auto-detect)')], default='ALL', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('stackable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='academic_sessions.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schools.school')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='students.class')),
                ('target_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='students.grade')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20)),
                ('gateway_order_id', models.CharField(max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('gateway_signature', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=20)),
                ('gateway_response', models.JSONField(default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('fee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='finance.feepayment')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Online Payment',
                'verbose_name_plural': 'Online Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'Easypaisa'), ('MANUAL', 'Manual/Offline')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict, help_text='Gateway-specific config: api_key, secret, webhook_secret')),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='schools.school')),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('scholarship_type', models.CharField(choices=[('MERIT', 'Merit-Based'), ('NEED', 'Need-Based'), ('SPORTS', 'Sports'), ('STAFF_CHILD', 'Staff Child'), ('OTHER', 'Other')], max_length=20)),
                ('coverage', models.CharField(choices=[('FULL', 'Full Fee Waiver'), ('PERCENTAGE', 'Percentage Off'), ('FIXED', 'Fixed Amount Off')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_recipients', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='academic_sessions.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='schools.school')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_sessions.academicyear')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.discount')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.scholarship')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Discount',
                'verbose_name_plural': 'Student Discounts',
            },
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['school', 'is_active'], name='finance_dis_school__aba9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['school', 'status'], name='finance_onl_school__44c150_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['gateway_order_id'], name='finance_onl_gateway_c2f326_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepayment',
            index=models.Index(fields=['student', 'status'], name='finance_onl_student_62f1b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('school', 'gateway')},
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['school', 'is_active'], name='finance_sch_school__dd3c50_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdiscount',
            index=models.Index(fields=['school', 'student', 'academic_year'], name='finance_stu_school__b6a490_idx'),
        ),
    ]
