# Generated by Django 5.2.11 on 2026-02-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_fee_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='finance_fee_school__c7f3b7_idx',
            old_name='finance_fee_school_feetype_idx',
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='month',
            field=models.IntegerField(help_text='Month number (1-12 for monthly, 0 for annual/admission/books/fine)'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, help_text='Fee amount (field name kept for backward compat; stores amount for any fee type)', max_digits=10),
        ),
    ]
