# Generated by Django 5.2.11 on 2026-02-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_rename_finance_fee_school_feetype_idx_finance_fee_school__c7f3b7_idx_and_more'),
        ('schools', '0012_school_ai_config'),
        ('students', '0010_fix_class_name_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="Auto-generated label, e.g. 'Khan Family (3 siblings)'", max_length=200)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_groups', to='schools.school')),
            ],
            options={
                'verbose_name': 'Sibling Group',
                'verbose_name_plural': 'Sibling Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiblingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='0 = eldest/first enrolled (pays full), 1+ = gets sibling discount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='finance.siblinggroup')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_membership', to='students.student')),
            ],
            options={
                'verbose_name': 'Sibling Group Member',
                'verbose_name_plural': 'Sibling Group Members',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SiblingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(help_text='Computed match score (0-100)')),
                ('match_signals', models.JSONField(default=dict, help_text="Which signals matched: {'parent_phone': true, 'parent_name': true, ...}")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sibling_suggestions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_suggestions', to='schools.school')),
                ('sibling_group', models.ForeignKey(blank=True, help_text='Set when suggestion is confirmed and group is created/joined', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.siblinggroup')),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_suggestions_as_a', to='students.student')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_suggestions_as_b', to='students.student')),
            ],
            options={
                'verbose_name': 'Sibling Suggestion',
                'verbose_name_plural': 'Sibling Suggestions',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='siblinggroup',
            index=models.Index(fields=['school', 'is_active'], name='finance_sib_school__e773fb_idx'),
        ),
        migrations.AddIndex(
            model_name='siblinggroupmember',
            index=models.Index(fields=['student'], name='finance_sib_student_fc4f32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='siblinggroupmember',
            unique_together={('group', 'student')},
        ),
        migrations.AddIndex(
            model_name='siblingsuggestion',
            index=models.Index(fields=['school', 'status'], name='finance_sib_school__377dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='siblingsuggestion',
            index=models.Index(fields=['student_a'], name='finance_sib_student_17c433_idx'),
        ),
        migrations.AddIndex(
            model_name='siblingsuggestion',
            index=models.Index(fields=['student_b'], name='finance_sib_student_f1722e_idx'),
        ),
        migrations.AddConstraint(
            model_name='siblingsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('school', 'student_a', 'student_b'), name='unique_pending_suggestion_pair'),
        ),
    ]
