# Generated by Django 5.2.11 on 2026-02-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_expensecategory_incomecategory_and_more'),
        ('students', '0010_fix_class_name_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Override fee for a specific student (takes precedence over class fee)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='students.student'),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentdiscount',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_discounts', to='students.student'),
        ),
    ]
