# Generated by Django 5.2.11 on 2026-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_protect_financial_records_from_student_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='base_monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original monthly fee from fee structure. Helps reconstruct amount_due when overridden.', max_digits=10, null=True),
        ),
    ]
