# Generated by Django 5.2.11 on 2026-03-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_feepayment_base_monthly_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this account (e.g., personal account for a staff member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
