# Generated by Django 5.2.11 on 2026-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_annualfeecategory_feestructure_annual_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('ADMISSION', 'Admission (Deprecated)'), ('BOOKS', 'Books (Deprecated)'), ('FINE', 'Fine (Deprecated)')], default='MONTHLY', help_text='Type of fee this payment record belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('ADMISSION', 'Admission (Deprecated)'), ('BOOKS', 'Books (Deprecated)'), ('FINE', 'Fine (Deprecated)')], default='MONTHLY', help_text='Type of fee: monthly recurring or annual', max_length=20),
        ),
    ]
