# Generated by Django 5.2.11 on 2026-03-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_feepayment_fee_type_and_more'),
        ('schools', '0014_school_exam_config'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='annual_category',
            field=models.ForeignKey(blank=True, help_text='Annual charge category (only used when fee_type=ANNUAL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='finance.annualfeecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('school', 'student', 'month', 'year', 'fee_type', 'annual_category')},
        ),
    ]
