# Generated by Django 5.2.11 on 2026-04-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_cleanup_duplicate_annual_categories'),
        ('schools', '0014_school_exam_config'),
        ('students', '0012_alter_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this monthly charge (e.g. Tuition Fee)', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fee_categories', to='schools.school')),
            ],
            options={
                'verbose_name': 'Monthly Fee Category',
                'verbose_name_plural': 'Monthly Fee Categories',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='monthly_category',
            field=models.ForeignKey(blank=True, help_text='Monthly charge category (only used when fee_type=MONTHLY)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='finance.monthlyfeecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='monthly_category',
            field=models.ForeignKey(blank=True, help_text='Monthly charge category (only used when fee_type=MONTHLY)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='finance.monthlyfeecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('school', 'student', 'month', 'year', 'fee_type', 'annual_category', 'monthly_category')},
        ),
    ]
