# Generated by Django 5.2.11 on 2026-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_backfill_monthly_fee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Hide this category and its expenses from staff members'),
        ),
    ]
