# Generated by Django 6.0.4 on 2026-07-07 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0013_schoolcalendarentry_affects_staff_affects_students'),
        ('finance', '0025_add_is_sensitive_to_expense_category'),
        ('schools', '0016_alter_school_module_entitlements'),
        ('students', '0012_alter_class_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_type', 'MONTHLY')), fields=('school', 'student', 'year', 'month', 'monthly_category'), name='uniq_monthly_fee_per_student_period_category'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_type', 'ANNUAL')), fields=('school', 'student', 'year', 'annual_category'), name='uniq_annual_fee_per_student_year_category'),
        ),
    ]
