# Generated by Django 5.2.11 on 2026-10-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_feepayment_uniq_monthly_fee_per_student_period_category_and_more'),
        ('student_exits', '0002_enrollmentbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='carried_from_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_fee_rows', to='student_exits.studentexit'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='handed_over_to_exit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_over_fee_rows', to='student_exits.studentexit'),
        ),
    ]
