# Generated by Django 5.2.11 on 2026-02-14 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Inventory categories',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, default='', help_text='Optional stock code', max_length=50)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('PKT', 'Packets'), ('BOX', 'Boxes'), ('KG', 'Kilograms'), ('LTR', 'Litres'), ('SET', 'Sets'), ('REAM', 'Reams'), ('DZN', 'Dozens'), ('MTR', 'Meters')], default='PCS', max_length=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this level')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Last known unit price', max_digits=10)),
                ('location', models.CharField(blank=True, default='', help_text='Storage location e.g. "Store Room A", "Lab Cabinet 3"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('condition_on_assign', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('condition_on_return', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='True while assigned, False after returned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='The person who has the item', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.inventoryitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DISPOSAL', 'Disposal')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Invoice/PO/receipt number', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Link to assignment for ISSUE/RETURN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.itemassignment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='schools.school')),
                ('vendor', models.ForeignKey(blank=True, help_text='Only for PURCHASE transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['school', 'category'], name='inventory_i_school__52c707_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('school', 'name', 'category')},
        ),
        migrations.AddIndex(
            model_name='itemassignment',
            index=models.Index(fields=['school', 'assigned_to'], name='inventory_i_school__1c610b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemassignment',
            index=models.Index(fields=['school', 'item'], name='inventory_i_school__130680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['school', 'item', '-date'], name='inventory_s_school__abbaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['school', 'transaction_type'], name='inventory_s_school__b5121b_idx'),
        ),
    ]
