# Generated by Django 6.0.1 on 2026-02-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0005_studentinvite_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Route name, e.g. 'Route 1 - North City'", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the route')),
                ('start_location', models.CharField(help_text='Starting point of the route', max_length=200)),
                ('end_location', models.CharField(help_text='Ending point of the route (usually the school)', max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Total route distance in kilometers', max_digits=6, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Estimated travel time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Transport Route',
                'verbose_name_plural': 'Transport Routes',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Stop name, e.g. 'Main Market'", max_length=100)),
                ('address', models.TextField(blank=True, default='', help_text='Full address of the stop')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude', max_digits=9, null=True)),
                ('stop_order', models.PositiveIntegerField(help_text='Order of this stop in the route (1, 2, 3, ...)')),
                ('pickup_time', models.TimeField(help_text='Scheduled pickup time at this stop')),
                ('drop_time', models.TimeField(help_text='Scheduled drop time at this stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.transportroute')),
            ],
            options={
                'verbose_name': 'Transport Stop',
                'verbose_name_plural': 'Transport Stops',
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('VAN', 'Van'), ('CAR', 'Car')], default='BUS', max_length=10)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum seating capacity')),
                ('make_model', models.CharField(blank=True, default='', help_text="Vehicle make and model, e.g. 'Toyota Coaster'", max_length=100)),
                ('driver_name', models.CharField(help_text='Name of the assigned driver', max_length=100)),
                ('driver_phone', models.CharField(help_text="Driver's contact phone number", max_length=20)),
                ('driver_license', models.CharField(blank=True, default='', help_text="Driver's license number", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_route', models.ForeignKey(blank=True, help_text='Route this vehicle is currently assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.transportroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='schools.school')),
            ],
            options={
                'verbose_name': 'Transport Vehicle',
                'verbose_name_plural': 'Transport Vehicles',
                'ordering': ['vehicle_number'],
                'unique_together': {('school', 'vehicle_number')},
            },
        ),
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the transport attendance record')),
                ('boarding_status', models.CharField(choices=[('BOARDED', 'Boarded'), ('NOT_BOARDED', 'Not Boarded'), ('ABSENT', 'Absent')], default='BOARDED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendance_records', to='students.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendance_records', to='transport.transportroute')),
            ],
            options={
                'verbose_name': 'Transport Attendance',
                'verbose_name_plural': 'Transport Attendance Records',
                'ordering': ['-date'],
                'unique_together': {('school', 'student', 'date', 'route')},
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('PICKUP', 'Pickup Only'), ('DROP', 'Drop Only'), ('BOTH', 'Both Pickup and Drop')], default='BOTH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='academic_sessions.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='students.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='transport.transportroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='transport.transportstop')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_assignments', to='transport.transportvehicle')),
            ],
            options={
                'verbose_name': 'Transport Assignment',
                'verbose_name_plural': 'Transport Assignments',
                'ordering': ['-created_at'],
                'unique_together': {('school', 'student', 'academic_year')},
            },
        ),
    ]
