# Generated by Django 5.2.11 on 2026-02-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0008_study_helper_message'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('TO_SCHOOL', 'To School'), ('FROM_SCHOOL', 'From School')], max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_journeys', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='students.student')),
                ('transport_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='transport.transportassignment')),
            ],
            options={
                'verbose_name': 'Student Journey',
                'verbose_name_plural': 'Student Journeys',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery % (0-100)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transport.studentjourney')),
            ],
            options={
                'verbose_name': 'Location Update',
                'verbose_name_plural': 'Location Updates',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['journey', '-timestamp'], name='transport_l_journey_fe568d_idx')],
            },
        ),
    ]
