# Generated by Django 5.2.11 on 2026-02-20 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        ('transport', '0003_transportroute_end_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transportvehicle',
            name='driver_user',
            field=models.ForeignKey(blank=True, help_text='Linked driver user account (for app-based tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RouteJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('TO_SCHOOL', 'To School'), ('FROM_SCHOOL', 'From School')], max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('tracking_mode', models.CharField(choices=[('DRIVER_APP', 'Driver App'), ('MANUAL', 'Manual (Admin)'), ('HARDWARE_GPS', 'Hardware GPS Device')], default='DRIVER_APP', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notified_stops', models.JSONField(blank=True, default=list, help_text='List of stop IDs that have triggered geofence notifications this journey')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_journeys', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_journeys', to='transport.transportroute')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_journeys', to='schools.school')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_journeys', to='transport.transportvehicle')),
            ],
            options={
                'verbose_name': 'Route Journey',
                'verbose_name_plural': 'Route Journeys',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(default=0, help_text='GPS accuracy in meters')),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery % (0-100)', null=True)),
                ('source', models.CharField(choices=[('APP', 'Driver App'), ('HARDWARE', 'Hardware GPS'), ('MANUAL', 'Manual Entry')], default='APP', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transport.routejourney')),
            ],
            options={
                'verbose_name': 'Route Location Update',
                'verbose_name_plural': 'Route Location Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='routejourney',
            index=models.Index(fields=['school', 'status'], name='transport_r_school__c8f99c_idx'),
        ),
        migrations.AddIndex(
            model_name='routelocationupdate',
            index=models.Index(fields=['journey', '-timestamp'], name='transport_r_journey_e34c55_idx'),
        ),
    ]
