# Generated by Django 6.0.1 on 2026-02-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('source', models.CharField(choices=[('IMAGE_AI', 'Image AI'), ('MANUAL', 'Manual')], default='IMAGE_AI', max_length=20)),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether WhatsApp notification was sent for this absence')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student__class_obj', 'student__roll_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the attendance register')),
                ('image_url', models.URLField(help_text='URL of the uploaded register image (Supabase)', max_length=500)),
                ('ai_output_json', models.JSONField(blank=True, help_text='JSON output from LLM: {matched: [], unmatched: [], confidence: 0.92}', null=True)),
                ('ocr_raw_text', models.TextField(blank=True, help_text='Raw text extracted by OCR')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0.00 - 1.00)', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Review Required'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_uploads', to='students.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Attendance Upload',
                'verbose_name_plural': 'Attendance Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
