# Generated by Django 6.0.1 on 2026-02-02 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_uploads', to='schools.school'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='The upload that created this record (if source is IMAGE_AI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='attendance.attendanceupload'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceupload',
            unique_together={('school', 'class_obj', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
    ]
