# Generated by Django 6.0.1 on 2026-02-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('attendance', '0004_add_multi_page_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancefeedback',
            new_name='attendance__school__a3ac7c_idx',
            old_name='attendance__school__idx',
        ),
        migrations.RenameIndex(
            model_name='attendancefeedback',
            new_name='attendance__correct_9756d9_idx',
            old_name='attendance__correct_idx',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academic_sessions.academicyear'),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Academic year this attendance belongs to (auto-resolved if not provided)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_uploads', to='academic_sessions.academicyear'),
        ),
    ]
