# Generated by Django 5.2.11 on 2026-02-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_session_scoped_roll_numbers'),
        ('attendance', '0005_add_academic_year_to_attendance'),
        ('face_attendance', '0001_initial'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0009_session_scoped_roll_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='face_session',
            field=models.ForeignKey(blank=True, help_text='The face session that created this record (if source is FACE_CAMERA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='face_attendance.faceattendancesession'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('IMAGE_AI', 'Image AI'), ('MANUAL', 'Manual'), ('FACE_CAMERA', 'Face Camera')], default='IMAGE_AI', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date', 'status'], name='attendance__school__a118c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceupload',
            index=models.Index(fields=['status'], name='attendance__status_f2ee4e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceupload',
            index=models.Index(fields=['-created_at'], name='attendance__created_1ef652_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceupload',
            index=models.Index(fields=['academic_year'], name='attendance__academi_998901_idx'),
        ),
    ]
