# Generated by Django 5.2.11 on 2026-02-21 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_face_session_and_more'),
        ('schools', '0012_school_ai_config'),
        ('students', '0010_fix_class_name_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='pipeline_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed pipeline execution info (providers tried, fallbacks, voting results)'),
        ),
        migrations.AddField(
            model_name='attendanceupload',
            name='pipeline_used',
            field=models.CharField(blank=True, default='', help_text='Which AI pipeline processed this upload (google, groq, tesseract, vote)', max_length=50),
        ),
        migrations.CreateModel(
            name='AccuracySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_predictions', models.IntegerField(default=0)),
                ('total_corrections', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('false_negatives', models.IntegerField(default=0)),
                ('name_mismatches', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy for this day (0.0 - 1.0)', null=True)),
                ('drift_detected', models.BooleanField(default=False)),
                ('drift_details', models.JSONField(blank=True, default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_snapshots', to='schools.school')),
            ],
            options={
                'verbose_name': 'Accuracy Snapshot',
                'verbose_name_plural': 'Accuracy Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['school', 'date'], name='attendance__school__5d0c4a_idx'), models.Index(fields=['drift_detected'], name='attendance__drift_d_ab35c5_idx')],
                'unique_together': {('school', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('CLASS_BULK', 'Bulk class absence'), ('STUDENT_PATTERN', 'Student pattern change'), ('UNUSUAL_DAY', 'Unusual day pattern')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_anomalies', to='students.class')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_anomalies', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_anomalies', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance Anomaly',
                'verbose_name_plural': 'Attendance Anomalies',
                'ordering': ['-date', '-severity'],
                'indexes': [models.Index(fields=['school', 'date'], name='attendance__school__64b264_idx'), models.Index(fields=['is_resolved'], name='attendance__is_reso_b8f45f_idx'), models.Index(fields=['anomaly_type'], name='attendance__anomaly_122e37_idx')],
            },
        ),
    ]
