# Generated by Django 5.2 on 2026-04-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0012_rename_academic_se_school__f1331a_idx_academic_se_school__3d73df_idx_and_more'),
        ('attendance', '0007_attendanceupload_pipeline_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceupload',
            name='session_class',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_uploads',
                to='academic_sessions.sessionclass',
                help_text='Session class/section for this upload (preferred over master class when available)',
            ),
        ),
        migrations.AddIndex(
            model_name='attendanceupload',
            index=models.Index(fields=['session_class'], name='attendance__session_313c7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceupload',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendanceupload',
            constraint=models.UniqueConstraint(
                condition=models.Q(session_class__isnull=False),
                fields=('school', 'session_class', 'date'),
                name='unique_upload_per_session_class_date',
            ),
        ),
        migrations.AddConstraint(
            model_name='attendanceupload',
            constraint=models.UniqueConstraint(
                condition=models.Q(session_class__isnull=True),
                fields=('school', 'class_obj', 'date'),
                name='unique_upload_per_master_class_date',
            ),
        ),
    ]
