# Generated by Django 5.2.11 on 2026-05-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendanceupload_session_class_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceupload',
            new_name='attendance__session_8905d0_idx',
            old_name='attendance__session_313c7f_idx',
        ),
    ]
