# Generated by Django 6.0.1 on 2026-02-13 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0010_alter_userschoolmembership_role'),
        ('students', '0004_student_address_student_admission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('relation_to_default', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], default='FATHER', max_length=20)),
                ('profile_photo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('document_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parent_leaves', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_leave_requests', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_leave_requests', to='students.student')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Parent Leave Request',
                'verbose_name_plural': 'Parent Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=20, unique=True)),
                ('relation', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=20)),
                ('parent_phone', models.CharField(blank=True, default='', help_text='Expected phone number for verification', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invites', to='students.student')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Parent Invite',
                'verbose_name_plural': 'Parent Invites',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this child')),
                ('can_pickup', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Parent-Child Link',
                'verbose_name_plural': 'Parent-Child Links',
            },
        ),
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_parent_messages', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='schools.school')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parent_messages', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Message',
                'verbose_name_plural': 'Parent Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread_id', 'created_at'], name='parents_par_thread__c01250_idx'), models.Index(fields=['recipient_user', 'is_read'], name='parents_par_recipie_2d9836_idx'), models.Index(fields=['school', 'student'], name='parents_par_school__bf6296_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['phone'], name='parents_par_phone_6bf5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='parentleaverequest',
            index=models.Index(fields=['school', 'status'], name='parents_par_school__666b16_idx'),
        ),
        migrations.AddIndex(
            model_name='parentleaverequest',
            index=models.Index(fields=['student', 'start_date'], name='parents_par_student_569936_idx'),
        ),
        migrations.AddIndex(
            model_name='parentinvite',
            index=models.Index(fields=['school', 'is_used'], name='parents_par_school__01f4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='parentinvite',
            index=models.Index(fields=['invite_code'], name='parents_par_invite__5de2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['school', 'parent'], name='parents_par_school__9a10db_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['student'], name='parents_par_student_07c496_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentchild',
            unique_together={('parent', 'student')},
        ),
    ]
