# Generated by Django 5.2.11 on 2026-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0001_initial'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0008_study_helper_message'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_obj', 'roll_number'), name='unique_roll_per_session_class'),
        ),
    ]
