# Generated by Django 5.2.11 on 2026-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_session_scoped_roll_numbers'),
        ('schools', '0011_alter_userschoolmembership_role'),
        ('students', '0010_fix_class_name_unique_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['academic_year', 'is_active', 'student'], name='academic_se_academi_492009_idx'),
        ),
    ]
