# Generated by Django 5.2.11 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0003_add_enrollment_query_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('REPEAT', 'Repeat'), ('TRANSFERRED', 'Transferred'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20),
        ),
    ]
