# Generated by Django 5.2.11 on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0004_alter_studentenrollment_status'),
        ('students', '0011_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('grade_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_classes', to='academic_sessions.academicyear')),
                ('class_obj', models.ForeignKey(blank=True, help_text='Optional link to master class for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_class_links', to='students.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_classes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Session Class',
                'verbose_name_plural': 'Session Classes',
                'ordering': ['academic_year', 'grade_level', 'section', 'display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionclass',
            index=models.Index(fields=['school', 'academic_year', 'is_active'], name='academic_ses_school__fb2d88_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionclass',
            index=models.Index(fields=['school', 'academic_year', 'grade_level', 'section'], name='academic_ses_school__f90f2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionclass',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'display_name', 'section'), name='unique_session_class_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='sessionclass',
            constraint=models.UniqueConstraint(condition=models.Q(('class_obj__isnull', False)), fields=('school', 'academic_year', 'class_obj'), name='unique_session_class_master_link_per_year'),
        ),
    ]
