# Generated by Django 5.2.11 on 2026-03-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0007_studentenrollment_session_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['academic_year', 'session_class', 'class_obj', 'roll_number'], 'verbose_name': 'Student Enrollment', 'verbose_name_plural': 'Student Enrollments'},
        ),
        migrations.RenameIndex(
            model_name='sessionclass',
            new_name='academic_se_school__c22706_idx',
            old_name='academic_ses_school__fb2d88_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionclass',
            new_name='academic_se_school__340c60_idx',
            old_name='academic_ses_school__f90f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='studentenrollment',
            new_name='academic_se_school__20370a_idx',
            old_name='academic_se_school__e5264f_idx',
        ),
    ]
