# Generated by Django 5.2.11 on 2026-03-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0009_schoolcalendarentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schoolcalendarentry',
            new_name='academic_se_school__7e8ecc_idx',
            old_name='academic_se_school__a89a6a_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcalendarentry',
            new_name='academic_se_school__c448b3_idx',
            old_name='academic_se_school__af95f0_idx',
        ),
    ]
