# Generated by Django 5.2.11 on 2026-04-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0011_promotion_operation_and_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionevent',
            new_name='academic_se_school__3d73df_idx',
            old_name='academic_se_school__f1331a_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionevent',
            new_name='academic_se_school__c0ef4a_idx',
            old_name='academic_se_school__8136b8_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionevent',
            new_name='academic_se_school__a468bb_idx',
            old_name='academic_se_school__4f6873_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionevent',
            new_name='academic_se_school__454c1f_idx',
            old_name='academic_se_school__eb141e_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoperation',
            new_name='academic_se_school__a6e6b6_idx',
            old_name='academic_se_school__2f37a4_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoperation',
            new_name='academic_se_school__f2f685_idx',
            old_name='academic_se_school__16bcb0_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoperation',
            new_name='academic_se_school__7b54d5_idx',
            old_name='academic_se_school__2f9fea_idx',
        ),
    ]
