# Generated by Django 6.0.4 on 2026-07-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0014_attendancerisksnapshot'),
        ('schools', '0018_school_academic_risk_config_school_inventory_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('total_students', models.IntegerField(default=0)),
                ('at_risk_count', models.IntegerField(default=0)),
                ('risk_levels', models.JSONField(blank=True, default=dict)),
                ('students', models.JSONField(blank=True, default=list)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risk_snapshots', to='academic_sessions.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_risk_snapshots', to='schools.school')),
            ],
            options={
                'verbose_name': 'Student Risk Snapshot',
                'verbose_name_plural': 'Student Risk Snapshots',
                'indexes': [models.Index(fields=['school', 'academic_year'], name='academic_se_school__a3af3f_idx')],
                'unique_together': {('school', 'academic_year')},
            },
        ),
    ]
