# Generated by Django 5.2.11 on 2026-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0015_studentrisksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='left_date',
            field=models.DateField(blank=True, help_text="Set when status becomes WITHDRAWN/TRANSFERRED. Month-precision cutoff: the enrollment is treated as covering every month up to and including left_date's month (see academic_sessions.utils.enrollment_covers_month). Cleared if the student is reactivated.", null=True),
        ),
    ]
