# Generated by Django 5.2.11 on 2026-10-10 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_studentenrollment_left_date'),
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0017_student_hard_delete_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='First day NOT in this placement; null = current.', null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['enrollment_id', 'start_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='studentenrollment',
            name='unique_roll_per_session_class_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='studentenrollment',
            name='unique_roll_per_legacy_class_enrollment',
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('session_class__isnull', False)), fields=('school', 'academic_year', 'session_class', 'roll_number'), name='unique_roll_per_session_class_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('session_class__isnull', True)), fields=('school', 'academic_year', 'class_obj', 'roll_number'), name='unique_roll_per_legacy_class_enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_placements', to='academic_sessions.academicyear'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.class'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='academic_sessions.studentenrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_placements', to='schools.school'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='session_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='academic_sessions.sessionclass'),
        ),
        migrations.AddField(
            model_name='enrollmentplacement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_placements', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='enrollmentplacement',
            index=models.Index(fields=['student', 'start_date'], name='academic_se_student_8c9164_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentplacement',
            index=models.Index(fields=['session_class', 'start_date'], name='academic_se_session_fe403a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentplacement',
            index=models.Index(fields=['school', 'academic_year', 'class_obj'], name='academic_se_school__64002b_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('enrollment',), name='one_open_placement_per_enrollment'),
        ),
    ]
