# Generated by Django 6.0.1 on 2026-02-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_organization_school_organization_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Deprecated: use school_memberships instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.school'),
        ),
    ]
