# Generated by Django 6.0.1 on 2026-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('HR_MANAGER', 'HR Manager'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
