# Generated by Django 5.2.11 on 2026-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_devicepushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('HR_MANAGER', 'HR Manager'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('DRIVER', 'Driver')], default='STAFF', max_length=20),
        ),
    ]
