# Generated by Django 5.2.11 on 2026-02-15 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0011_alter_userschoolmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('REPORT_GENERATION', 'Report Generation'), ('PAYSLIP_GENERATION', 'Payslip Generation'), ('TIMETABLE_GENERATION', 'Timetable Generation'), ('FEE_GENERATION', 'Fee Generation'), ('BULK_PROMOTION', 'Bulk Promotion'), ('PROMOTION_ADVISOR', 'Promotion Advisor')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='schools.school')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'triggered_by', '-created_at'], name='core_backgr_school__3622fc_idx')],
            },
        ),
    ]
