# Generated by Django 5.2.11 on 2026-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('REPORT_GENERATION', 'Report Generation'), ('PAYSLIP_GENERATION', 'Payslip Generation'), ('TIMETABLE_GENERATION', 'Timetable Generation'), ('FEE_GENERATION', 'Fee Generation'), ('BULK_PROMOTION', 'Bulk Promotion'), ('PROMOTION_ADVISOR', 'Promotion Advisor'), ('FACE_ATTENDANCE', 'Face Attendance Processing')], max_length=30),
        ),
    ]
