# Generated by Django 6.0.4 on 2026-05-25 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_backgroundtask_task_type'),
        ('schools', '0016_alter_school_module_entitlements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('generate_questions', 'Generate Questions'), ('generate_lesson', 'Generate Lesson Plan'), ('suggest_toc', 'Suggest TOC'), ('embed_content', 'Embed Content'), ('classify_bloom', 'Classify Bloom Level')], max_length=40)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='schools.school')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_type', 'status'], name='core_aijob_job_typ_5f1da7_idx'), models.Index(fields=['school', 'status'], name='core_aijob_school__c3814f_idx')],
            },
        ),
    ]
