# Generated by Django 6.0.4 on 2026-08-06 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_queuedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='queuedjob',
            new_name='core_queued_status_47b043_idx',
            old_name='core_queuedj_status_4f5080_idx',
        ),
        migrations.RenameIndex(
            model_name='queuedjob',
            new_name='core_queued_status_a31a8d_idx',
            old_name='core_queuedj_status_85a300_idx',
        ),
        migrations.RenameIndex(
            model_name='queuedjob',
            new_name='core_queued_school__c7d6a6_idx',
            old_name='core_queuedj_school__f57bf2_idx',
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['-created_at'], name='core_admina_created_e436ec_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['actor', '-created_at'], name='core_admina_actor_i_ec43ad_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_type', 'target_id'], name='core_admina_target__a189d0_idx'),
        ),
    ]
