# Generated by Django 6.0.4 on 2026-08-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminactionlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('REPORT_GENERATION', 'Report Generation'), ('PAYSLIP_GENERATION', 'Payslip Generation'), ('TIMETABLE_GENERATION', 'Timetable Generation'), ('FEE_GENERATION', 'Fee Generation'), ('BULK_PROMOTION', 'Bulk Promotion'), ('PROMOTION_ADVISOR', 'Promotion Advisor'), ('FACE_ATTENDANCE', 'Face Attendance Processing'), ('EXAM_QUESTION_GENERATION', 'Exam Question Generation')], max_length=30),
        ),
    ]
