# Generated by Django 5.2.11 on 2026-10-09 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_login_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user_agent',
            field=models.CharField(blank=True, db_default='', default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['school_id', '-created_at'], name='core_admina_school__c920ec_idx'),
        ),
    ]
