# Generated by Django 5.2.11 on 2026-10-04 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_type', models.CharField(choices=[('WITHDRAWN', 'Withdrawn (left school)'), ('TRANSFERRED', 'Transferred (to another branch)')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALIZED', 'Finalized'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('leaving_date', models.DateField(help_text='First day the student is gone (same meaning as StudentEnrollment.left_date).')),
                ('reason', models.TextField(blank=True, default='')),
                ('remove_records_after_leaving', models.BooleanField(default=False, help_text='Delete attendance/marks on or after the leaving date when finalizing (backed up in the admin audit log first).')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Class, roll, pending fees and clearance as they were at finalization.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_school', models.ForeignKey(blank=True, help_text='Required for TRANSFERRED; must be another school of the same organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_exits', to='schools.school')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exits', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Exit',
                'verbose_name_plural': 'Student Exits',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExitClearanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FEES', 'Pending fees'), ('LIBRARY', 'Library books'), ('GATE_PASS', 'Open gate pass')], max_length=20)),
                ('state', models.CharField(choices=[('CLEAR', 'Clear'), ('OPEN', 'Open'), ('WAIVED', 'Waived')], default='CLEAR', max_length=10)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('waived_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('waiver_reason', models.TextField(blank=True, default='')),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='student_exits.studentexit')),
            ],
            options={
                'verbose_name': 'Exit Clearance Item',
                'verbose_name_plural': 'Exit Clearance Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='studentexit',
            index=models.Index(fields=['school', 'status'], name='student_exi_school__d8ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexit',
            index=models.Index(fields=['student', 'status'], name='student_exi_student_68cf58_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('student',), name='one_open_exit_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='exitclearanceitem',
            unique_together={('exit', 'kind')},
        ),
    ]
