# Generated by Django 5.2.11 on 2026-10-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_rename_hr_manager_to_manager'),
        ('student_exits', '0001_initial'),
        ('students', '0013_student_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day away (the leaving date).')),
                ('end_date', models.DateField(blank=True, help_text='First day back. Empty while the student is still away.', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Why they came back (set at re-admission).')),
                ('readmitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exit', models.ForeignKey(blank=True, help_text='The exit that opened this break (empty for backfilled or legacy cases).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaks', to='student_exits.studentexit')),
                ('readmitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_breaks', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_breaks', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment Break',
                'verbose_name_plural': 'Enrollment Breaks',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['student', 'start_date'], name='student_exi_student_781943_idx'), models.Index(fields=['school', 'start_date'], name='student_exi_school__e8b1d0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='one_open_break_per_student'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='break_ends_after_it_starts')],
            },
        ),
    ]
