# Generated by Django 5.2.11 on 2026-10-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_studentenrollment_left_date'),
        ('student_exits', '0002_enrollmentbreak'),
        ('students', '0014_student_transferred_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexit',
            name='destination_roll_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentexit',
            name='destination_session_class',
            field=models.ForeignKey(blank=True, help_text='Class (section) at the destination branch the student joins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academic_sessions.sessionclass'),
        ),
        migrations.AddField(
            model_name='studentexit',
            name='destination_student',
            field=models.ForeignKey(blank=True, help_text='The new student record created at the destination when this transfer is finalized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in_exit', to='students.student'),
        ),
        migrations.AlterField(
            model_name='exitclearanceitem',
            name='state',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('OPEN', 'Open'), ('WAIVED', 'Waived'), ('CARRIED', 'Carried to new branch')], default='CLEAR', max_length=10),
        ),
    ]
